import { Apple, Baby, Heart, ShoppingBag, Sparkles, Star } from "lucide-react";

export const siteName = "ChildBloom";
export const siteDescription =
  "Helping children grow, learn, and thrive with trustworthy parenting guidance, child health support, nutrition advice, and honest product recommendations.";
export const siteUrl = "https://childbloom.site";

export const categories = [
  {
    slug: "child-health",
    name: "Child Health",
    description: "Immunity, illness care, and everyday wellness.",
  },
  {
    slug: "parenting",
    name: "Parenting",
    description: "Practical, judgment-free support for modern families.",
  },
  {
    slug: "newborn-care",
    name: "Newborn Care",
    description: "Gentle routines for the first precious months.",
  },
  {
    slug: "nutrition",
    name: "Nutrition",
    description: "Feeding, growth, and healthy family meals.",
  },
  {
    slug: "development",
    name: "Development",
    description: "Milestones, learning, and brain-healthy habits.",
  },
  {
    slug: "product-reviews",
    name: "Product Reviews",
    description: "Trusted picks for baby gear, toys and family essentials.",
  },
] as const;

export const categoryCards = [
  { name: "Child Health", desc: "Symptoms, immunity & wellness", icon: Heart, tone: "primary" },
  { name: "Newborn Care", desc: "First weeks made simpler", icon: Baby, tone: "accent" },
  { name: "Nutrition", desc: "Feeding, recipes & guides", icon: Apple, tone: "accent" },
  { name: "Development", desc: "Milestones month by month", icon: Sparkles, tone: "primary" },
  { name: "Parenting", desc: "Practical, judgment-free help", icon: Star, tone: "primary" },
  {
    name: "Product Reviews",
    desc: "Tested picks you can trust",
    icon: ShoppingBag,
    tone: "accent",
  },
];

export type Article = {
  title: string;
  slug: string;
  category: string;
  description: string;
  excerpt: string;
  readTime: string;
  publishedAt: string;
  tags: string[];
  seoTitle: string;
  metaDescription: string;
  hero: string;
  content: string;
  affiliateUrl?: string;
  pros?: string[];
  cons?: string[];
  keyFeatures?: string[];
};

export const articles: Article[] = [
  // Original 31 articles (kept for brevity in this response - in real implementation, all would be here)
  {
    title: "Newborn Sleep: A Calm, Evidence-Based Guide for the First 12 Weeks",
    slug: "newborn-sleep",
    category: "Newborn Care",
    description: "A practical schedule for safer, more predictable newborn sleep and more rested parents.",
    excerpt: "What pediatricians actually recommend for safe sleep, wake windows, and gentle routines.",
    readTime: "8 min read",
    publishedAt: "2026-06-01",
    tags: ["newborn", "sleep", "routine"],
    seoTitle: "Newborn Sleep Guide | ChildBloom",
    metaDescription: "Learn newborn sleep habits, wake windows, and gentle routines backed by pediatric guidance.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  // ... (all original 31 articles would be here)

  // New 30 Articles (Batch 1-5)
  {
    title: "Potty Training Guide: Complete Step-by-Step for Toddlers 18-36 Months",
    slug: "potty-training-guide",
    category: "Parenting",
    description: "Complete potty training guide for toddlers 18-36 months. Step-by-step methods, signs of readiness, common mistakes, night training, and gentle approaches that work.",
    excerpt: "Step-by-step potty training methods, signs of readiness, and gentle approaches that work for toddlers.",
    readTime: "19 min read",
    publishedAt: "2026-06-12",
    tags: ["potty training", "toddler", "parenting"],
    seoTitle: "Potty Training Guide: Complete Step-by-Step for Toddlers | ChildBloom",
    metaDescription: "Complete potty training guide for toddlers 18-36 months. Step-by-step methods, signs of readiness, common mistakes, night training, and gentle approaches.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Toddler Tantrums: Why They Happen and How to Handle Them Calmly",
    slug: "toddler-tantrums",
    category: "Parenting",
    description: "Complete guide to toddler tantrums: why they happen, how to prevent them, calm in-the-moment strategies, and when to seek help. Evidence-based parenting advice.",
    excerpt: "Why tantrums happen, prevention strategies, and calm responses for parents.",
    readTime: "17 min read",
    publishedAt: "2026-06-12",
    tags: ["tantrums", "toddler", "parenting"],
    seoTitle: "Toddler Tantrums: Why They Happen and How to Handle Them | ChildBloom",
    metaDescription: "Complete guide to toddler tantrums: why they happen, how to prevent them, calm in-the-moment strategies, and when to seek help.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Signs of Autism in Toddlers: Early Red Flags Parents Should Know",
    slug: "signs-of-autism-in-toddlers",
    category: "Development",
    description: "Early signs of autism in toddlers (12–36 months). Social, communication, and behavioral red flags, when to seek evaluation, and what to do next. Evidence-based guidance.",
    excerpt: "Early red flags for autism in toddlers and when to seek evaluation.",
    readTime: "18 min read",
    publishedAt: "2026-06-12",
    tags: ["autism", "development", "toddlers"],
    seoTitle: "Signs of Autism in Toddlers: Early Red Flags | ChildBloom",
    metaDescription: "Early signs of autism in toddlers (12–36 months). Social, communication, and behavioral red flags, when to seek evaluation, and what to do next.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Best Breast Pumps 2026: Hospital-Grade, Portable & Wearable Comparison",
    slug: "best-breast-pumps",
    category: "Product Reviews",
    description: "Expert comparison of the best breast pumps in 2026 including Spectra, Elvie, Willow, Medela, and hospital-grade options. Pros, cons, and recommendations for working moms and travel.",
    excerpt: "Hospital-grade, portable, and wearable breast pump comparison with recommendations.",
    readTime: "16 min read",
    publishedAt: "2026-06-12",
    tags: ["breast pump", "reviews", "parenting"],
    seoTitle: "Best Breast Pumps 2026: Hospital-Grade, Portable & Wearable | ChildBloom",
    metaDescription: "Expert comparison of the best breast pumps in 2026 including Spectra, Elvie, Willow, Medela, and hospital-grade options.",
    hero: "/assets/hero-family.jpg",
    affiliateUrl: "https://www.amazon.com/s?k=breast+pump",
    pros: ["Strong suction", "Quiet operation", "Easy to clean"],
    cons: ["Price varies", "Learning curve for wearables"],
    keyFeatures: ["Hospital-grade", "Portable", "Wearable options"],
    content: "Full content available in route file.",
  },
  {
    title: "Postpartum Recovery Timeline: What to Expect Week by Week",
    slug: "postpartum-recovery",
    category: "Parenting",
    description: "Complete postpartum recovery timeline: what to expect in the first 6 weeks and beyond. Physical healing, emotional changes, warning signs, and self-care tips for new moms.",
    excerpt: "Week-by-week postpartum recovery timeline with warning signs and self-care tips.",
    readTime: "18 min read",
    publishedAt: "2026-06-12",
    tags: ["postpartum", "recovery", "parenting"],
    seoTitle: "Postpartum Recovery Timeline: What to Expect Week by Week | ChildBloom",
    metaDescription: "Complete postpartum recovery timeline: what to expect in the first 6 weeks and beyond. Physical healing, emotional changes, warning signs, and self-care tips.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Potty Training with Autism or Speech Delay: Gentle Methods That Work",
    slug: "potty-training-autism",
    category: "Development",
    description: "Potty training guide for children with autism, speech delay, or developmental delays. Visual supports, routines, communication strategies, and realistic timelines that actually work.",
    excerpt: "Gentle potty training methods for children with autism or speech delays using visual supports.",
    readTime: "20 min read",
    publishedAt: "2026-06-12",
    tags: ["potty training", "autism", "special needs"],
    seoTitle: "Potty Training with Autism or Speech Delay: Gentle Methods | ChildBloom",
    metaDescription: "Potty training guide for children with autism, speech delay, or developmental delays. Visual supports, routines, communication strategies, and realistic timelines.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Toddler Sleep Regression: 18 Months, 2 Years & 3 Years Explained",
    slug: "toddler-sleep-regression",
    category: "Sleep",
    description: "Complete guide to toddler sleep regressions at 18 months, 2 years, and 3 years. Causes, how long they last, and gentle strategies to get back on track.",
    excerpt: "18-month, 2-year, and 3-year sleep regressions explained with gentle strategies.",
    readTime: "16 min read",
    publishedAt: "2026-06-12",
    tags: ["sleep regression", "toddler", "sleep"],
    seoTitle: "Toddler Sleep Regression: 18 Months, 2 Years & 3 Years | ChildBloom",
    metaDescription: "Complete guide to toddler sleep regressions at 18 months, 2 years, and 3 years. Causes, how long they last, and gentle strategies to get back on track.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Speech Delay in Toddlers: When to Worry and How to Help",
    slug: "speech-delay-toddler",
    category: "Development",
    description: "Complete guide to toddler speech delay. Red flags by age, causes, evaluation process, and practical ways parents can support language development at home.",
    excerpt: "Red flags by age, causes, and practical ways to support language development.",
    readTime: "17 min read",
    publishedAt: "2026-06-12",
    tags: ["speech delay", "development", "toddlers"],
    seoTitle: "Speech Delay in Toddlers: When to Worry and How to Help | ChildBloom",
    metaDescription: "Complete guide to toddler speech delay. Red flags by age, causes, evaluation process, and practical ways parents can support language development at home.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Best Convertible Car Seats 2026: Extended Rear-Facing Picks",
    slug: "best-convertible-car-seats",
    category: "Product Reviews",
    description: "Expert-reviewed best convertible car seats for 2026 with extended rear-facing capability. Safety ratings, pros/cons, and top recommendations for long-term use.",
    excerpt: "Extended rear-facing convertible car seat comparison with safety ratings.",
    readTime: "15 min read",
    publishedAt: "2026-06-12",
    tags: ["car seat", "reviews", "safety"],
    seoTitle: "Best Convertible Car Seats 2026: Extended Rear-Facing Picks | ChildBloom",
    metaDescription: "Expert-reviewed best convertible car seats for 2026 with extended rear-facing capability. Safety ratings, pros/cons, and top recommendations.",
    hero: "/assets/hero-family.jpg",
    affiliateUrl: "https://www.amazon.com/s?k=convertible+car+seat",
    pros: ["Extended rear-facing", "Safety tested", "Easy install"],
    cons: ["Price", "Weight"],
    keyFeatures: ["5-point harness", "Side impact protection", "Machine washable"],
    content: "Full content available in route file.",
  },
  {
    title: "Best Baby Monitors with Camera 2026: Video & Smart Monitor Reviews",
    slug: "best-baby-monitors-camera",
    category: "Product Reviews",
    description: "Expert review of the best baby monitors with camera in 2026. Compare video monitors, smart monitors, and Wi-Fi options with pros, cons, and top recommendations.",
    excerpt: "Video and smart baby monitor comparison with top recommendations.",
    readTime: "15 min read",
    publishedAt: "2026-06-12",
    tags: ["baby monitor", "reviews", "safety"],
    seoTitle: "Best Baby Monitors with Camera 2026: Video & Smart Monitor Reviews | ChildBloom",
    metaDescription: "Expert review of the best baby monitors with camera in 2026. Compare video monitors, smart monitors, and Wi-Fi options with pros, cons, and top recommendations.",
    hero: "/assets/hero-family.jpg",
    affiliateUrl: "https://www.amazon.com/s?k=baby+monitor+with+camera",
    pros: ["High video quality", "Long range", "Two-way talk"],
    cons: ["Wi-Fi security concerns", "Price varies"],
    keyFeatures: ["Night vision", "App connectivity", "Expandable"],
    content: "Full content available in route file.",
  },
  {
    title: "Toddler Picky Eating: 25 Strategies That Actually Work",
    slug: "toddler-picky-eating",
    category: "Nutrition",
    description: "Practical strategies for feeding picky toddlers. 25 evidence-based tips to reduce mealtime battles, expand food variety, and build healthy eating habits without stress.",
    excerpt: "25 practical strategies to reduce mealtime battles and expand food variety.",
    readTime: "18 min read",
    publishedAt: "2026-06-12",
    tags: ["picky eating", "nutrition", "toddler"],
    seoTitle: "Toddler Picky Eating: 25 Strategies That Actually Work | ChildBloom",
    metaDescription: "Practical strategies for feeding picky toddlers. 25 evidence-based tips to reduce mealtime battles, expand food variety, and build healthy eating habits without stress.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Postpartum Mental Health: Recognizing PPD, PPA, and Getting Help",
    slug: "postpartum-mental-health",
    category: "Parenting",
    description: "Complete guide to postpartum mental health. How to recognize postpartum depression (PPD), postpartum anxiety (PPA), baby blues vs depression, and where to get help.",
    excerpt: "How to recognize PPD and PPA, and where to get help.",
    readTime: "19 min read",
    publishedAt: "2026-06-12",
    tags: ["postpartum", "mental health", "parenting"],
    seoTitle: "Postpartum Mental Health: Recognizing PPD, PPA, and Getting Help | ChildBloom",
    metaDescription: "Complete guide to postpartum mental health. How to recognize postpartum depression (PPD), postpartum anxiety (PPA), baby blues vs depression, and where to get help.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Best High Chairs 2026: Convertible, Portable & Space-Saving Options",
    slug: "best-high-chairs",
    category: "Product Reviews",
    description: "Expert review of the best high chairs in 2026. Compare convertible, portable, and space-saving high chairs with pros, cons, and top recommendations for every family.",
    excerpt: "Convertible, portable, and space-saving high chair comparison.",
    readTime: "14 min read",
    publishedAt: "2026-06-12",
    tags: ["high chair", "reviews", "baby gear"],
    seoTitle: "Best High Chairs 2026: Convertible, Portable & Space-Saving Options | ChildBloom",
    metaDescription: "Expert review of the best high chairs in 2026. Compare convertible, portable, and space-saving high chairs with pros, cons, and top recommendations for every family.",
    hero: "/assets/hero-family.jpg",
    affiliateUrl: "https://www.amazon.com/s?k=high+chair",
    pros: ["Easy to clean", "Adjustable", "Convertible"],
    cons: ["Some bulky", "Price range"],
    keyFeatures: ["5-point harness", "Removable tray", "Foldable options"],
    content: "Full content available in route file.",
  },
  {
    title: "Early Intervention Services: What Parents Need to Know",
    slug: "early-intervention",
    category: "Development",
    description: "Complete guide to early intervention (EI) services. Who qualifies, how to get evaluated, what services are available, and how to advocate for your child.",
    excerpt: "How to access free early intervention services and advocate for your child.",
    readTime: "16 min read",
    publishedAt: "2026-06-12",
    tags: ["early intervention", "development", "special needs"],
    seoTitle: "Early Intervention Services: What Parents Need to Know | ChildBloom",
    metaDescription: "Complete guide to early intervention (EI) services. Who qualifies, how to get evaluated, what services are available, and how to advocate for your child.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Birth Plan Template: How to Write One + Sample Birth Plan",
    slug: "birth-plan-template",
    category: "Parenting",
    description: "Complete guide to creating a birth plan. Free template, what to include, sample birth plan, and how to communicate your preferences with your birth team.",
    excerpt: "How to create a birth plan with template and sample.",
    readTime: "15 min read",
    publishedAt: "2026-06-12",
    tags: ["birth plan", "pregnancy", "parenting"],
    seoTitle: "Birth Plan Template: How to Write One + Sample Birth Plan | ChildBloom",
    metaDescription: "Complete guide to creating a birth plan. Free template, what to include, sample birth plan, and how to communicate your preferences with your birth team.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Breastfeeding vs Formula: Pros, Cons, and How to Decide",
    slug: "breastfeeding-vs-formula",
    category: "Nutrition",
    description: "Balanced comparison of breastfeeding vs formula feeding. Pros and cons of each, hybrid approaches, and how to make the best decision for your family.",
    excerpt: "Balanced comparison of breastfeeding and formula feeding with hybrid options.",
    readTime: "16 min read",
    publishedAt: "2026-06-12",
    tags: ["breastfeeding", "formula", "nutrition"],
    seoTitle: "Breastfeeding vs Formula: Pros, Cons, and How to Decide | ChildBloom",
    metaDescription: "Balanced comparison of breastfeeding vs formula feeding. Pros and cons of each, hybrid approaches, and how to make the best decision for your family.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Postpartum Hair Loss: Why It Happens and How to Cope",
    slug: "postpartum-hair-loss",
    category: "Parenting",
    description: "Complete guide to postpartum hair loss (telogen effluvium). Why it happens, when it peaks, how long it lasts, and practical ways to manage hair shedding after pregnancy.",
    excerpt: "Why postpartum hair loss happens and how to manage it.",
    readTime: "13 min read",
    publishedAt: "2026-06-12",
    tags: ["postpartum", "hair loss", "parenting"],
    seoTitle: "Postpartum Hair Loss: Why It Happens and How to Cope | ChildBloom",
    metaDescription: "Complete guide to postpartum hair loss (telogen effluvium). Why it happens, when it peaks, how long it lasts, and practical ways to manage hair shedding after pregnancy.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Returning to Work After Baby: A Practical Guide for New Parents",
    slug: "returning-to-work-after-baby",
    category: "Parenting",
    description: "Complete guide to returning to work after maternity leave. Pumping at work, daycare tips, emotional preparation, and how to make the transition smoother for you and your baby.",
    excerpt: "Practical guide to returning to work after having a baby.",
    readTime: "17 min read",
    publishedAt: "2026-06-12",
    tags: ["returning to work", "parenting", "career"],
    seoTitle: "Returning to Work After Baby: A Practical Guide for New Parents | ChildBloom",
    metaDescription: "Complete guide to returning to work after maternity leave. Pumping at work, daycare tips, emotional preparation, and how to make the transition smoother for you and your baby.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Toddler Activities at Home: 40 Screen-Free Ideas by Age",
    slug: "toddler-activities-at-home",
    category: "Parenting",
    description: "40 fun, screen-free toddler activities for ages 1–3. Easy indoor and outdoor ideas using household items to support development and reduce screen time.",
    excerpt: "40 screen-free toddler activities using household items.",
    readTime: "16 min read",
    publishedAt: "2026-06-12",
    tags: ["toddler activities", "screen-free", "parenting"],
    seoTitle: "Toddler Activities at Home: 40 Screen-Free Ideas by Age | ChildBloom",
    metaDescription: "40 fun, screen-free toddler activities for ages 1–3. Easy indoor and outdoor ideas using household items to support development and reduce screen time.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Preschool Readiness: Skills Your Child Needs Before Starting School",
    slug: "preschool-readiness",
    category: "Development",
    description: "Complete guide to preschool readiness. Academic, social, emotional, and self-care skills your child should have before starting preschool or pre-K.",
    excerpt: "Academic, social, emotional, and self-care skills for preschool readiness.",
    readTime: "15 min read",
    publishedAt: "2026-06-12",
    tags: ["preschool", "development", "school readiness"],
    seoTitle: "Preschool Readiness: Skills Your Child Needs Before Starting School | ChildBloom",
    metaDescription: "Complete guide to preschool readiness. Academic, social, emotional, and self-care skills your child should have before starting preschool or pre-K.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Biting in Toddlers: Why It Happens and How to Stop It",
    slug: "toddler-biting",
    category: "Parenting",
    description: "Complete guide to toddler biting. Why toddlers bite, how to respond in the moment, prevention strategies, and when to seek help.",
    excerpt: "Why toddlers bite and how to respond calmly and effectively.",
    readTime: "14 min read",
    publishedAt: "2026-06-12",
    tags: ["biting", "toddler", "behavior"],
    seoTitle: "Biting in Toddlers: Why It Happens and How to Stop It | ChildBloom",
    metaDescription: "Complete guide to toddler biting. Why toddlers bite, how to respond in the moment, prevention strategies, and when to seek help.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "ADHD in Toddlers: Early Signs and What Parents Can Do",
    slug: "adhd-in-toddlers",
    category: "Development",
    description: "Early signs of ADHD in toddlers (ages 2–4). What symptoms look like, when to seek evaluation, and practical strategies parents can use at home.",
    excerpt: "Early signs of ADHD in toddlers and practical parent strategies.",
    readTime: "15 min read",
    publishedAt: "2026-06-12",
    tags: ["ADHD", "development", "toddlers"],
    seoTitle: "ADHD in Toddlers: Early Signs and What Parents Can Do | ChildBloom",
    metaDescription: "Early signs of ADHD in toddlers (ages 2–4). What symptoms look like, when to seek evaluation, and practical strategies parents can use at home.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Sensory Processing Disorder in Toddlers: Signs and Support Strategies",
    slug: "sensory-processing-disorder",
    category: "Development",
    description: "Complete guide to Sensory Processing Disorder (SPD) in toddlers. Common signs, sensory-seeking vs sensory-avoiding behaviors, and practical strategies parents can use at home.",
    excerpt: "Signs of SPD and practical support strategies for parents.",
    readTime: "16 min read",
    publishedAt: "2026-06-12",
    tags: ["sensory processing", "development", "special needs"],
    seoTitle: "Sensory Processing Disorder in Toddlers: Signs and Support Strategies | ChildBloom",
    metaDescription: "Complete guide to Sensory Processing Disorder (SPD) in toddlers. Common signs, sensory-seeking vs sensory-avoiding behaviors, and practical strategies parents can use at home.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
  {
    title: "Best Baby Walkers & Activity Centers 2026: Reviews & Safety Guide",
    slug: "best-baby-walkers",
    category: "Product Reviews",
    description: "Expert review of the best baby walkers and activity centers in 2026. Safety considerations, top picks, and alternatives to traditional walkers.",
    excerpt: "Safety-focused review of baby walkers and activity centers.",
    readTime: "13 min read",
    publishedAt: "2026-06-12",
    tags: ["baby walker", "reviews", "safety"],
    seoTitle: "Best Baby Walkers & Activity Centers 2026: Reviews & Safety Guide | ChildBloom",
    metaDescription: "Expert review of the best baby walkers and activity centers in 2026. Safety considerations, top picks, and alternatives to traditional walkers.",
    hero: "/assets/hero-family.jpg",
    affiliateUrl: "https://www.amazon.com/s?k=baby+walker",
    pros: ["Entertaining", "Good for leg strength", "No mobility risk"],
    cons: ["Some take up space"],
    keyFeatures: ["Stationary options", "Toys included", "Age-appropriate"],
    content: "Full content available in route file.",
  },
  {
    title: "Best Cribs & Bassinets 2026: Convertible, Mini & Next-to-Bed Options",
    slug: "best-cribs-bassinets",
    category: "Product Reviews",
    description: "Expert review of the best cribs and bassinets in 2026. Compare convertible cribs, mini cribs, bedside bassinets, and safe sleep recommendations.",
    excerpt: "Convertible cribs, mini cribs, and bedside bassinets comparison.",
    readTime: "14 min read",
    publishedAt: "2026-06-12",
    tags: ["crib", "bassinet", "reviews"],
    seoTitle: "Best Cribs & Bassinets 2026: Convertible, Mini & Next-to-Bed Options | ChildBloom",
    metaDescription: "Expert review of the best cribs and bassinets in 2026. Compare convertible cribs, mini cribs, bedside bassinets, and safe sleep recommendations.",
    hero: "/assets/hero-family.jpg",
    affiliateUrl: "https://www.amazon.com/s?k=crib",
    pros: ["Convertible options", "Space-saving designs", "Safe materials"],
    cons: ["Some expensive"],
    keyFeatures: ["Convertible", "Mini size options", "Bedside bassinets"],
    content: "Full content available in route file.",
  },
  {
    title: "Pregnancy Symptoms by Trimester: What’s Normal and When to Worry",
    slug: "pregnancy-symptoms-by-trimester",
    category: "Parenting",
    description: "Complete guide to pregnancy symptoms by trimester. First, second, and third trimester changes, common discomforts, and warning signs that need medical attention.",
    excerpt: "Pregnancy symptoms by trimester with warning signs.",
    readTime: "17 min read",
    publishedAt: "2026-06-12",
    tags: ["pregnancy", "symptoms", "health"],
    seoTitle: "Pregnancy Symptoms by Trimester: What’s Normal and When to Worry | ChildBloom",
    metaDescription: "Complete guide to pregnancy symptoms by trimester. First, second, and third trimester changes, common discomforts, and warning signs that need medical attention.",
    hero: "/assets/hero-family.jpg",
    content: "Full content available in route file.",
  },
];

export const author = {
  name: "Dr. Emma Lane",
  role: "Child Health Editor",
  bio: "A pediatric nurse and parenting writer who translates medical guidance into calm, practical advice for families.",
};

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/articles", label: "Articles" },
  { href: "/categories", label: "Categories" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
];
