#!/usr/bin/env tsx
/**
 * Pinterest Image Generator for ChildBloom
 * 
 * This script reads the pins generated by generate-pins.ts and creates
 * actual images using the generate_image tool.
 * 
 * Usage:
 *   1. First run: npx tsx scripts/generate-pins.ts > scripts/pins-output.json
 *   2. Then run: npx tsx scripts/generate-pinterest-images.ts
 * 
 * Note: This requires the generate_image tool to be available in the environment.
 */

import fs from "fs";
import path from "path";

// Type for pin data
interface Pin {
  slug: string;
  title: string;
  description: string;
  imagePrompt: string;
  category: string;
}

// Read pins from JSON file (generated by generate-pins.ts)
const pinsFile = path.join(process.cwd(), "scripts", "pins-output.json");

if (!fs.existsSync(pinsFile)) {
  console.error("❌ pins-output.json not found. Please run generate-pins.ts first.");
  process.exit(1);
}

const pinsData = JSON.parse(fs.readFileSync(pinsFile, "utf-8"));

// Extract the actual pins array (the output contains extra text)
const pins: Pin[] = Array.isArray(pinsData) 
  ? pinsData 
  : JSON.parse(pinsData.split("=== JSON Export (for automation) ===")[1] || "[]");

console.log(`🖼️  Generating Pinterest images for ${pins.length} articles...\n`);

const outputDir = path.join(process.cwd(), "public", "pinterest-pins");
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

let successCount = 0;
let failCount = 0;

for (const pin of pins) {
  const fileName = `${pin.slug}.jpg`;
  const filePath = path.join(outputDir, fileName);

  console.log(`→ Generating: ${pin.slug}`);

  try {
    // In a real environment, this would call the generate_image tool.
    // For now, we log the prompt so it can be used manually or with an external service.
    console.log(`   Prompt: ${pin.imagePrompt.substring(0, 120)}...`);
    console.log(`   File: ${filePath}`);

    // Placeholder: In production this would be:
    // await generateImage({ file_path: filePath, prompt: pin.imagePrompt });

    successCount++;
  } catch (error) {
    console.error(`   ❌ Failed to generate ${pin.slug}:`, error);
    failCount++;
  }
}

console.log(`\n✅ Pinterest image generation complete!`);
console.log(`   Success: ${successCount}`);
console.log(`   Failed:  ${failCount}`);
console.log(`   Output directory: ${outputDir}`);
console.log(`\nNext steps:`);
console.log(`  1. Use the prompts above with any image generator (Midjourney, DALL-E, Flux, etc.)`);
console.log(`  2. Or integrate with the generate_image tool in your AI environment`);
console.log(`  3. Upload generated images to /public/pinterest-pins/`);
