/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MedicalDisclaimerRouteImport } from './routes/medical-disclaimer'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as GoSlugRouteImport } from './routes/go/$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors/$slug'
import { Route as ArticlesWhenToCallPediatricianRouteImport } from './routes/articles/when-to-call-pediatrician'
import { Route as ArticlesVaccinationGuideRouteImport } from './routes/articles/vaccination-guide'
import { Route as ArticlesToddlerTantrumsRouteImport } from './routes/articles/toddler-tantrums'
import { Route as ArticlesToddlerSleepRegressionRouteImport } from './routes/articles/toddler-sleep-regression'
import { Route as ArticlesToddlerSleepProblemsRouteImport } from './routes/articles/toddler-sleep-problems'
import { Route as ArticlesToddlerScreenTimeRouteImport } from './routes/articles/toddler-screen-time'
import { Route as ArticlesToddlerRegressionRouteImport } from './routes/articles/toddler-regression'
import { Route as ArticlesToddlerPickyEatingRouteImport } from './routes/articles/toddler-picky-eating'
import { Route as ArticlesToddlerNutritionTipsRouteImport } from './routes/articles/toddler-nutrition-tips'
import { Route as ArticlesToddlerNotTalkingRouteImport } from './routes/articles/toddler-not-talking'
import { Route as ArticlesToddlerHittingRouteImport } from './routes/articles/toddler-hitting'
import { Route as ArticlesToddlerBitingRouteImport } from './routes/articles/toddler-biting'
import { Route as ArticlesToddlerActivitiesAtHomeRouteImport } from './routes/articles/toddler-activities-at-home'
import { Route as ArticlesStartingSolidsGuideRouteImport } from './routes/articles/starting-solids-guide'
import { Route as ArticlesStartingSolidsRouteImport } from './routes/articles/starting-solids'
import { Route as ArticlesSpeechMilestonesRouteImport } from './routes/articles/speech-milestones'
import { Route as ArticlesSpeechDevelopmentGuideRouteImport } from './routes/articles/speech-development-guide'
import { Route as ArticlesSpeechDelayToddlerRouteImport } from './routes/articles/speech-delay-toddler'
import { Route as ArticlesSleepTrainingMethodsRouteImport } from './routes/articles/sleep-training-methods'
import { Route as ArticlesSignsOfAutismInToddlersRouteImport } from './routes/articles/signs-of-autism-in-toddlers'
import { Route as ArticlesSensoryProcessingDisorderRouteImport } from './routes/articles/sensory-processing-disorder'
import { Route as ArticlesReturningToWorkAfterBabyRouteImport } from './routes/articles/returning-to-work-after-baby'
import { Route as ArticlesPreschoolReadinessRouteImport } from './routes/articles/preschool-readiness'
import { Route as ArticlesPregnancySymptomsByTrimesterRouteImport } from './routes/articles/pregnancy-symptoms-by-trimester'
import { Route as ArticlesPottyTrainingGuideRouteImport } from './routes/articles/potty-training-guide'
import { Route as ArticlesPottyTrainingAutismRouteImport } from './routes/articles/potty-training-autism'
import { Route as ArticlesPostpartumRecoveryRouteImport } from './routes/articles/postpartum-recovery'
import { Route as ArticlesPostpartumMentalHealthRouteImport } from './routes/articles/postpartum-mental-health'
import { Route as ArticlesPostpartumHairLossRouteImport } from './routes/articles/postpartum-hair-loss'
import { Route as ArticlesParentingSurvivalGuideRouteImport } from './routes/articles/parenting-survival-guide'
import { Route as ArticlesParentingHacksRouteImport } from './routes/articles/parenting-hacks'
import { Route as ArticlesNewbornSleepRouteImport } from './routes/articles/newborn-sleep'
import { Route as ArticlesNewbornEssentialsChecklistRouteImport } from './routes/articles/newborn-essentials-checklist'
import { Route as ArticlesNewbornCareGuideRouteImport } from './routes/articles/newborn-care-guide'
import { Route as ArticlesFeverInChildrenRouteImport } from './routes/articles/fever-in-children'
import { Route as ArticlesEarlyInterventionRouteImport } from './routes/articles/early-intervention'
import { Route as ArticlesCoSleepingSafetyRouteImport } from './routes/articles/co-sleeping-safety'
import { Route as ArticlesChildNutritionGuideRouteImport } from './routes/articles/child-nutrition-guide'
import { Route as ArticlesChildFeverHomeRemediesRouteImport } from './routes/articles/child-fever-home-remedies'
import { Route as ArticlesChildFeverGuideRouteImport } from './routes/articles/child-fever-guide'
import { Route as ArticlesChildDevelopmentMilestonesRouteImport } from './routes/articles/child-development-milestones'
import { Route as ArticlesBreastfeedingVsFormulaRouteImport } from './routes/articles/breastfeeding-vs-formula'
import { Route as ArticlesBirthPlanTemplateRouteImport } from './routes/articles/birth-plan-template'
import { Route as ArticlesBestStrollersRouteImport } from './routes/articles/best-strollers'
import { Route as ArticlesBestHighChairsRouteImport } from './routes/articles/best-high-chairs'
import { Route as ArticlesBestEducationalToysRouteImport } from './routes/articles/best-educational-toys'
import { Route as ArticlesBestDiaperBagsRouteImport } from './routes/articles/best-diaper-bags'
import { Route as ArticlesBestCribsBassinetsRouteImport } from './routes/articles/best-cribs-bassinets'
import { Route as ArticlesBestConvertibleCarSeatsRouteImport } from './routes/articles/best-convertible-car-seats'
import { Route as ArticlesBestCarSeatsRouteImport } from './routes/articles/best-car-seats'
import { Route as ArticlesBestBreastPumpsWorkingMomsRouteImport } from './routes/articles/best-breast-pumps-working-moms'
import { Route as ArticlesBestBreastPumpsRouteImport } from './routes/articles/best-breast-pumps'
import { Route as ArticlesBestBabyWalkersRouteImport } from './routes/articles/best-baby-walkers'
import { Route as ArticlesBestBabyThermometersRouteImport } from './routes/articles/best-baby-thermometers'
import { Route as ArticlesBestBabySleepProductsRouteImport } from './routes/articles/best-baby-sleep-products'
import { Route as ArticlesBestBabyMonitorsCameraRouteImport } from './routes/articles/best-baby-monitors-camera'
import { Route as ArticlesBestBabyMonitorsRouteImport } from './routes/articles/best-baby-monitors'
import { Route as ArticlesBestBabyFormulaRouteImport } from './routes/articles/best-baby-formula'
import { Route as ArticlesBestBabyFoodMakersRouteImport } from './routes/articles/best-baby-food-makers'
import { Route as ArticlesBestBabyCarriersRouteImport } from './routes/articles/best-baby-carriers'
import { Route as ArticlesBestBabyBottlesRouteImport } from './routes/articles/best-baby-bottles'
import { Route as ArticlesBestBabyBooksRouteImport } from './routes/articles/best-baby-books'
import { Route as ArticlesBabyTeethingSymptomsRouteImport } from './routes/articles/baby-teething-symptoms'
import { Route as ArticlesBabySleepGuideRouteImport } from './routes/articles/baby-sleep-guide'
import { Route as ArticlesBabyMilestonesByMonthRouteImport } from './routes/articles/baby-milestones-by-month'
import { Route as ArticlesBabyGrowthSpurtsRouteImport } from './routes/articles/baby-growth-spurts'
import { Route as ArticlesAdhdInToddlersRouteImport } from './routes/articles/adhd-in-toddlers'
import { Route as ArticlesTemplateRouteImport } from './routes/articles/_template'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as AdminSubscribersRouteImport } from './routes/admin/subscribers'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as AdminArticlesNewRouteImport } from './routes/admin/articles/new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin/articles/$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalDisclaimerRoute = MedicalDisclaimerRouteImport.update({
  id: '/medical-disclaimer',
  path: '/medical-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GoSlugRoute = GoSlugRouteImport.update({
  id: '/go/$slug',
  path: '/go/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesWhenToCallPediatricianRoute =
  ArticlesWhenToCallPediatricianRouteImport.update({
    id: '/when-to-call-pediatrician',
    path: '/when-to-call-pediatrician',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesVaccinationGuideRoute =
  ArticlesVaccinationGuideRouteImport.update({
    id: '/vaccination-guide',
    path: '/vaccination-guide',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesToddlerTantrumsRoute = ArticlesToddlerTantrumsRouteImport.update({
  id: '/toddler-tantrums',
  path: '/toddler-tantrums',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesToddlerSleepRegressionRoute =
  ArticlesToddlerSleepRegressionRouteImport.update({
    id: '/toddler-sleep-regression',
    path: '/toddler-sleep-regression',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesToddlerSleepProblemsRoute =
  ArticlesToddlerSleepProblemsRouteImport.update({
    id: '/toddler-sleep-problems',
    path: '/toddler-sleep-problems',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesToddlerScreenTimeRoute =
  ArticlesToddlerScreenTimeRouteImport.update({
    id: '/toddler-screen-time',
    path: '/toddler-screen-time',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesToddlerRegressionRoute =
  ArticlesToddlerRegressionRouteImport.update({
    id: '/toddler-regression',
    path: '/toddler-regression',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesToddlerPickyEatingRoute =
  ArticlesToddlerPickyEatingRouteImport.update({
    id: '/toddler-picky-eating',
    path: '/toddler-picky-eating',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesToddlerNutritionTipsRoute =
  ArticlesToddlerNutritionTipsRouteImport.update({
    id: '/toddler-nutrition-tips',
    path: '/toddler-nutrition-tips',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesToddlerNotTalkingRoute =
  ArticlesToddlerNotTalkingRouteImport.update({
    id: '/toddler-not-talking',
    path: '/toddler-not-talking',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesToddlerHittingRoute = ArticlesToddlerHittingRouteImport.update({
  id: '/toddler-hitting',
  path: '/toddler-hitting',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesToddlerBitingRoute = ArticlesToddlerBitingRouteImport.update({
  id: '/toddler-biting',
  path: '/toddler-biting',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesToddlerActivitiesAtHomeRoute =
  ArticlesToddlerActivitiesAtHomeRouteImport.update({
    id: '/toddler-activities-at-home',
    path: '/toddler-activities-at-home',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesStartingSolidsGuideRoute =
  ArticlesStartingSolidsGuideRouteImport.update({
    id: '/starting-solids-guide',
    path: '/starting-solids-guide',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesStartingSolidsRoute = ArticlesStartingSolidsRouteImport.update({
  id: '/starting-solids',
  path: '/starting-solids',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesSpeechMilestonesRoute =
  ArticlesSpeechMilestonesRouteImport.update({
    id: '/speech-milestones',
    path: '/speech-milestones',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesSpeechDevelopmentGuideRoute =
  ArticlesSpeechDevelopmentGuideRouteImport.update({
    id: '/speech-development-guide',
    path: '/speech-development-guide',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesSpeechDelayToddlerRoute =
  ArticlesSpeechDelayToddlerRouteImport.update({
    id: '/speech-delay-toddler',
    path: '/speech-delay-toddler',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesSleepTrainingMethodsRoute =
  ArticlesSleepTrainingMethodsRouteImport.update({
    id: '/sleep-training-methods',
    path: '/sleep-training-methods',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesSignsOfAutismInToddlersRoute =
  ArticlesSignsOfAutismInToddlersRouteImport.update({
    id: '/signs-of-autism-in-toddlers',
    path: '/signs-of-autism-in-toddlers',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesSensoryProcessingDisorderRoute =
  ArticlesSensoryProcessingDisorderRouteImport.update({
    id: '/sensory-processing-disorder',
    path: '/sensory-processing-disorder',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesReturningToWorkAfterBabyRoute =
  ArticlesReturningToWorkAfterBabyRouteImport.update({
    id: '/returning-to-work-after-baby',
    path: '/returning-to-work-after-baby',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesPreschoolReadinessRoute =
  ArticlesPreschoolReadinessRouteImport.update({
    id: '/preschool-readiness',
    path: '/preschool-readiness',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesPregnancySymptomsByTrimesterRoute =
  ArticlesPregnancySymptomsByTrimesterRouteImport.update({
    id: '/pregnancy-symptoms-by-trimester',
    path: '/pregnancy-symptoms-by-trimester',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesPottyTrainingGuideRoute =
  ArticlesPottyTrainingGuideRouteImport.update({
    id: '/potty-training-guide',
    path: '/potty-training-guide',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesPottyTrainingAutismRoute =
  ArticlesPottyTrainingAutismRouteImport.update({
    id: '/potty-training-autism',
    path: '/potty-training-autism',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesPostpartumRecoveryRoute =
  ArticlesPostpartumRecoveryRouteImport.update({
    id: '/postpartum-recovery',
    path: '/postpartum-recovery',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesPostpartumMentalHealthRoute =
  ArticlesPostpartumMentalHealthRouteImport.update({
    id: '/postpartum-mental-health',
    path: '/postpartum-mental-health',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesPostpartumHairLossRoute =
  ArticlesPostpartumHairLossRouteImport.update({
    id: '/postpartum-hair-loss',
    path: '/postpartum-hair-loss',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesParentingSurvivalGuideRoute =
  ArticlesParentingSurvivalGuideRouteImport.update({
    id: '/parenting-survival-guide',
    path: '/parenting-survival-guide',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesParentingHacksRoute = ArticlesParentingHacksRouteImport.update({
  id: '/parenting-hacks',
  path: '/parenting-hacks',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesNewbornSleepRoute = ArticlesNewbornSleepRouteImport.update({
  id: '/newborn-sleep',
  path: '/newborn-sleep',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesNewbornEssentialsChecklistRoute =
  ArticlesNewbornEssentialsChecklistRouteImport.update({
    id: '/newborn-essentials-checklist',
    path: '/newborn-essentials-checklist',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesNewbornCareGuideRoute =
  ArticlesNewbornCareGuideRouteImport.update({
    id: '/newborn-care-guide',
    path: '/newborn-care-guide',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesFeverInChildrenRoute = ArticlesFeverInChildrenRouteImport.update({
  id: '/fever-in-children',
  path: '/fever-in-children',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesEarlyInterventionRoute =
  ArticlesEarlyInterventionRouteImport.update({
    id: '/early-intervention',
    path: '/early-intervention',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesCoSleepingSafetyRoute =
  ArticlesCoSleepingSafetyRouteImport.update({
    id: '/co-sleeping-safety',
    path: '/co-sleeping-safety',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesChildNutritionGuideRoute =
  ArticlesChildNutritionGuideRouteImport.update({
    id: '/child-nutrition-guide',
    path: '/child-nutrition-guide',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesChildFeverHomeRemediesRoute =
  ArticlesChildFeverHomeRemediesRouteImport.update({
    id: '/child-fever-home-remedies',
    path: '/child-fever-home-remedies',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesChildFeverGuideRoute = ArticlesChildFeverGuideRouteImport.update({
  id: '/child-fever-guide',
  path: '/child-fever-guide',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesChildDevelopmentMilestonesRoute =
  ArticlesChildDevelopmentMilestonesRouteImport.update({
    id: '/child-development-milestones',
    path: '/child-development-milestones',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBreastfeedingVsFormulaRoute =
  ArticlesBreastfeedingVsFormulaRouteImport.update({
    id: '/breastfeeding-vs-formula',
    path: '/breastfeeding-vs-formula',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBirthPlanTemplateRoute =
  ArticlesBirthPlanTemplateRouteImport.update({
    id: '/birth-plan-template',
    path: '/birth-plan-template',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestStrollersRoute = ArticlesBestStrollersRouteImport.update({
  id: '/best-strollers',
  path: '/best-strollers',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBestHighChairsRoute = ArticlesBestHighChairsRouteImport.update({
  id: '/best-high-chairs',
  path: '/best-high-chairs',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBestEducationalToysRoute =
  ArticlesBestEducationalToysRouteImport.update({
    id: '/best-educational-toys',
    path: '/best-educational-toys',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestDiaperBagsRoute = ArticlesBestDiaperBagsRouteImport.update({
  id: '/best-diaper-bags',
  path: '/best-diaper-bags',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBestCribsBassinetsRoute =
  ArticlesBestCribsBassinetsRouteImport.update({
    id: '/best-cribs-bassinets',
    path: '/best-cribs-bassinets',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestConvertibleCarSeatsRoute =
  ArticlesBestConvertibleCarSeatsRouteImport.update({
    id: '/best-convertible-car-seats',
    path: '/best-convertible-car-seats',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestCarSeatsRoute = ArticlesBestCarSeatsRouteImport.update({
  id: '/best-car-seats',
  path: '/best-car-seats',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBestBreastPumpsWorkingMomsRoute =
  ArticlesBestBreastPumpsWorkingMomsRouteImport.update({
    id: '/best-breast-pumps-working-moms',
    path: '/best-breast-pumps-working-moms',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestBreastPumpsRoute = ArticlesBestBreastPumpsRouteImport.update({
  id: '/best-breast-pumps',
  path: '/best-breast-pumps',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBestBabyWalkersRoute = ArticlesBestBabyWalkersRouteImport.update({
  id: '/best-baby-walkers',
  path: '/best-baby-walkers',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBestBabyThermometersRoute =
  ArticlesBestBabyThermometersRouteImport.update({
    id: '/best-baby-thermometers',
    path: '/best-baby-thermometers',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestBabySleepProductsRoute =
  ArticlesBestBabySleepProductsRouteImport.update({
    id: '/best-baby-sleep-products',
    path: '/best-baby-sleep-products',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestBabyMonitorsCameraRoute =
  ArticlesBestBabyMonitorsCameraRouteImport.update({
    id: '/best-baby-monitors-camera',
    path: '/best-baby-monitors-camera',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestBabyMonitorsRoute =
  ArticlesBestBabyMonitorsRouteImport.update({
    id: '/best-baby-monitors',
    path: '/best-baby-monitors',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestBabyFormulaRoute = ArticlesBestBabyFormulaRouteImport.update({
  id: '/best-baby-formula',
  path: '/best-baby-formula',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBestBabyFoodMakersRoute =
  ArticlesBestBabyFoodMakersRouteImport.update({
    id: '/best-baby-food-makers',
    path: '/best-baby-food-makers',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestBabyCarriersRoute =
  ArticlesBestBabyCarriersRouteImport.update({
    id: '/best-baby-carriers',
    path: '/best-baby-carriers',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestBabyBottlesRoute = ArticlesBestBabyBottlesRouteImport.update({
  id: '/best-baby-bottles',
  path: '/best-baby-bottles',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBestBabyBooksRoute = ArticlesBestBabyBooksRouteImport.update({
  id: '/best-baby-books',
  path: '/best-baby-books',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBabyTeethingSymptomsRoute =
  ArticlesBabyTeethingSymptomsRouteImport.update({
    id: '/baby-teething-symptoms',
    path: '/baby-teething-symptoms',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBabySleepGuideRoute = ArticlesBabySleepGuideRouteImport.update({
  id: '/baby-sleep-guide',
  path: '/baby-sleep-guide',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesBabyMilestonesByMonthRoute =
  ArticlesBabyMilestonesByMonthRouteImport.update({
    id: '/baby-milestones-by-month',
    path: '/baby-milestones-by-month',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBabyGrowthSpurtsRoute =
  ArticlesBabyGrowthSpurtsRouteImport.update({
    id: '/baby-growth-spurts',
    path: '/baby-growth-spurts',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesAdhdInToddlersRoute = ArticlesAdhdInToddlersRouteImport.update({
  id: '/adhd-in-toddlers',
  path: '/adhd-in-toddlers',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesTemplateRoute = ArticlesTemplateRouteImport.update({
  id: '/_template',
  getParentRoute: () => ArticlesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/adhd-in-toddlers': typeof ArticlesAdhdInToddlersRoute
  '/articles/baby-growth-spurts': typeof ArticlesBabyGrowthSpurtsRoute
  '/articles/baby-milestones-by-month': typeof ArticlesBabyMilestonesByMonthRoute
  '/articles/baby-sleep-guide': typeof ArticlesBabySleepGuideRoute
  '/articles/baby-teething-symptoms': typeof ArticlesBabyTeethingSymptomsRoute
  '/articles/best-baby-books': typeof ArticlesBestBabyBooksRoute
  '/articles/best-baby-bottles': typeof ArticlesBestBabyBottlesRoute
  '/articles/best-baby-carriers': typeof ArticlesBestBabyCarriersRoute
  '/articles/best-baby-food-makers': typeof ArticlesBestBabyFoodMakersRoute
  '/articles/best-baby-formula': typeof ArticlesBestBabyFormulaRoute
  '/articles/best-baby-monitors': typeof ArticlesBestBabyMonitorsRoute
  '/articles/best-baby-monitors-camera': typeof ArticlesBestBabyMonitorsCameraRoute
  '/articles/best-baby-sleep-products': typeof ArticlesBestBabySleepProductsRoute
  '/articles/best-baby-thermometers': typeof ArticlesBestBabyThermometersRoute
  '/articles/best-baby-walkers': typeof ArticlesBestBabyWalkersRoute
  '/articles/best-breast-pumps': typeof ArticlesBestBreastPumpsRoute
  '/articles/best-breast-pumps-working-moms': typeof ArticlesBestBreastPumpsWorkingMomsRoute
  '/articles/best-car-seats': typeof ArticlesBestCarSeatsRoute
  '/articles/best-convertible-car-seats': typeof ArticlesBestConvertibleCarSeatsRoute
  '/articles/best-cribs-bassinets': typeof ArticlesBestCribsBassinetsRoute
  '/articles/best-diaper-bags': typeof ArticlesBestDiaperBagsRoute
  '/articles/best-educational-toys': typeof ArticlesBestEducationalToysRoute
  '/articles/best-high-chairs': typeof ArticlesBestHighChairsRoute
  '/articles/best-strollers': typeof ArticlesBestStrollersRoute
  '/articles/birth-plan-template': typeof ArticlesBirthPlanTemplateRoute
  '/articles/breastfeeding-vs-formula': typeof ArticlesBreastfeedingVsFormulaRoute
  '/articles/child-development-milestones': typeof ArticlesChildDevelopmentMilestonesRoute
  '/articles/child-fever-guide': typeof ArticlesChildFeverGuideRoute
  '/articles/child-fever-home-remedies': typeof ArticlesChildFeverHomeRemediesRoute
  '/articles/child-nutrition-guide': typeof ArticlesChildNutritionGuideRoute
  '/articles/co-sleeping-safety': typeof ArticlesCoSleepingSafetyRoute
  '/articles/early-intervention': typeof ArticlesEarlyInterventionRoute
  '/articles/fever-in-children': typeof ArticlesFeverInChildrenRoute
  '/articles/newborn-care-guide': typeof ArticlesNewbornCareGuideRoute
  '/articles/newborn-essentials-checklist': typeof ArticlesNewbornEssentialsChecklistRoute
  '/articles/newborn-sleep': typeof ArticlesNewbornSleepRoute
  '/articles/parenting-hacks': typeof ArticlesParentingHacksRoute
  '/articles/parenting-survival-guide': typeof ArticlesParentingSurvivalGuideRoute
  '/articles/postpartum-hair-loss': typeof ArticlesPostpartumHairLossRoute
  '/articles/postpartum-mental-health': typeof ArticlesPostpartumMentalHealthRoute
  '/articles/postpartum-recovery': typeof ArticlesPostpartumRecoveryRoute
  '/articles/potty-training-autism': typeof ArticlesPottyTrainingAutismRoute
  '/articles/potty-training-guide': typeof ArticlesPottyTrainingGuideRoute
  '/articles/pregnancy-symptoms-by-trimester': typeof ArticlesPregnancySymptomsByTrimesterRoute
  '/articles/preschool-readiness': typeof ArticlesPreschoolReadinessRoute
  '/articles/returning-to-work-after-baby': typeof ArticlesReturningToWorkAfterBabyRoute
  '/articles/sensory-processing-disorder': typeof ArticlesSensoryProcessingDisorderRoute
  '/articles/signs-of-autism-in-toddlers': typeof ArticlesSignsOfAutismInToddlersRoute
  '/articles/sleep-training-methods': typeof ArticlesSleepTrainingMethodsRoute
  '/articles/speech-delay-toddler': typeof ArticlesSpeechDelayToddlerRoute
  '/articles/speech-development-guide': typeof ArticlesSpeechDevelopmentGuideRoute
  '/articles/speech-milestones': typeof ArticlesSpeechMilestonesRoute
  '/articles/starting-solids': typeof ArticlesStartingSolidsRoute
  '/articles/starting-solids-guide': typeof ArticlesStartingSolidsGuideRoute
  '/articles/toddler-activities-at-home': typeof ArticlesToddlerActivitiesAtHomeRoute
  '/articles/toddler-biting': typeof ArticlesToddlerBitingRoute
  '/articles/toddler-hitting': typeof ArticlesToddlerHittingRoute
  '/articles/toddler-not-talking': typeof ArticlesToddlerNotTalkingRoute
  '/articles/toddler-nutrition-tips': typeof ArticlesToddlerNutritionTipsRoute
  '/articles/toddler-picky-eating': typeof ArticlesToddlerPickyEatingRoute
  '/articles/toddler-regression': typeof ArticlesToddlerRegressionRoute
  '/articles/toddler-screen-time': typeof ArticlesToddlerScreenTimeRoute
  '/articles/toddler-sleep-problems': typeof ArticlesToddlerSleepProblemsRoute
  '/articles/toddler-sleep-regression': typeof ArticlesToddlerSleepRegressionRoute
  '/articles/toddler-tantrums': typeof ArticlesToddlerTantrumsRoute
  '/articles/vaccination-guide': typeof ArticlesVaccinationGuideRoute
  '/articles/when-to-call-pediatrician': typeof ArticlesWhenToCallPediatricianRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/articles/adhd-in-toddlers': typeof ArticlesAdhdInToddlersRoute
  '/articles/baby-growth-spurts': typeof ArticlesBabyGrowthSpurtsRoute
  '/articles/baby-milestones-by-month': typeof ArticlesBabyMilestonesByMonthRoute
  '/articles/baby-sleep-guide': typeof ArticlesBabySleepGuideRoute
  '/articles/baby-teething-symptoms': typeof ArticlesBabyTeethingSymptomsRoute
  '/articles/best-baby-books': typeof ArticlesBestBabyBooksRoute
  '/articles/best-baby-bottles': typeof ArticlesBestBabyBottlesRoute
  '/articles/best-baby-carriers': typeof ArticlesBestBabyCarriersRoute
  '/articles/best-baby-food-makers': typeof ArticlesBestBabyFoodMakersRoute
  '/articles/best-baby-formula': typeof ArticlesBestBabyFormulaRoute
  '/articles/best-baby-monitors': typeof ArticlesBestBabyMonitorsRoute
  '/articles/best-baby-monitors-camera': typeof ArticlesBestBabyMonitorsCameraRoute
  '/articles/best-baby-sleep-products': typeof ArticlesBestBabySleepProductsRoute
  '/articles/best-baby-thermometers': typeof ArticlesBestBabyThermometersRoute
  '/articles/best-baby-walkers': typeof ArticlesBestBabyWalkersRoute
  '/articles/best-breast-pumps': typeof ArticlesBestBreastPumpsRoute
  '/articles/best-breast-pumps-working-moms': typeof ArticlesBestBreastPumpsWorkingMomsRoute
  '/articles/best-car-seats': typeof ArticlesBestCarSeatsRoute
  '/articles/best-convertible-car-seats': typeof ArticlesBestConvertibleCarSeatsRoute
  '/articles/best-cribs-bassinets': typeof ArticlesBestCribsBassinetsRoute
  '/articles/best-diaper-bags': typeof ArticlesBestDiaperBagsRoute
  '/articles/best-educational-toys': typeof ArticlesBestEducationalToysRoute
  '/articles/best-high-chairs': typeof ArticlesBestHighChairsRoute
  '/articles/best-strollers': typeof ArticlesBestStrollersRoute
  '/articles/birth-plan-template': typeof ArticlesBirthPlanTemplateRoute
  '/articles/breastfeeding-vs-formula': typeof ArticlesBreastfeedingVsFormulaRoute
  '/articles/child-development-milestones': typeof ArticlesChildDevelopmentMilestonesRoute
  '/articles/child-fever-guide': typeof ArticlesChildFeverGuideRoute
  '/articles/child-fever-home-remedies': typeof ArticlesChildFeverHomeRemediesRoute
  '/articles/child-nutrition-guide': typeof ArticlesChildNutritionGuideRoute
  '/articles/co-sleeping-safety': typeof ArticlesCoSleepingSafetyRoute
  '/articles/early-intervention': typeof ArticlesEarlyInterventionRoute
  '/articles/fever-in-children': typeof ArticlesFeverInChildrenRoute
  '/articles/newborn-care-guide': typeof ArticlesNewbornCareGuideRoute
  '/articles/newborn-essentials-checklist': typeof ArticlesNewbornEssentialsChecklistRoute
  '/articles/newborn-sleep': typeof ArticlesNewbornSleepRoute
  '/articles/parenting-hacks': typeof ArticlesParentingHacksRoute
  '/articles/parenting-survival-guide': typeof ArticlesParentingSurvivalGuideRoute
  '/articles/postpartum-hair-loss': typeof ArticlesPostpartumHairLossRoute
  '/articles/postpartum-mental-health': typeof ArticlesPostpartumMentalHealthRoute
  '/articles/postpartum-recovery': typeof ArticlesPostpartumRecoveryRoute
  '/articles/potty-training-autism': typeof ArticlesPottyTrainingAutismRoute
  '/articles/potty-training-guide': typeof ArticlesPottyTrainingGuideRoute
  '/articles/pregnancy-symptoms-by-trimester': typeof ArticlesPregnancySymptomsByTrimesterRoute
  '/articles/preschool-readiness': typeof ArticlesPreschoolReadinessRoute
  '/articles/returning-to-work-after-baby': typeof ArticlesReturningToWorkAfterBabyRoute
  '/articles/sensory-processing-disorder': typeof ArticlesSensoryProcessingDisorderRoute
  '/articles/signs-of-autism-in-toddlers': typeof ArticlesSignsOfAutismInToddlersRoute
  '/articles/sleep-training-methods': typeof ArticlesSleepTrainingMethodsRoute
  '/articles/speech-delay-toddler': typeof ArticlesSpeechDelayToddlerRoute
  '/articles/speech-development-guide': typeof ArticlesSpeechDevelopmentGuideRoute
  '/articles/speech-milestones': typeof ArticlesSpeechMilestonesRoute
  '/articles/starting-solids': typeof ArticlesStartingSolidsRoute
  '/articles/starting-solids-guide': typeof ArticlesStartingSolidsGuideRoute
  '/articles/toddler-activities-at-home': typeof ArticlesToddlerActivitiesAtHomeRoute
  '/articles/toddler-biting': typeof ArticlesToddlerBitingRoute
  '/articles/toddler-hitting': typeof ArticlesToddlerHittingRoute
  '/articles/toddler-not-talking': typeof ArticlesToddlerNotTalkingRoute
  '/articles/toddler-nutrition-tips': typeof ArticlesToddlerNutritionTipsRoute
  '/articles/toddler-picky-eating': typeof ArticlesToddlerPickyEatingRoute
  '/articles/toddler-regression': typeof ArticlesToddlerRegressionRoute
  '/articles/toddler-screen-time': typeof ArticlesToddlerScreenTimeRoute
  '/articles/toddler-sleep-problems': typeof ArticlesToddlerSleepProblemsRoute
  '/articles/toddler-sleep-regression': typeof ArticlesToddlerSleepRegressionRoute
  '/articles/toddler-tantrums': typeof ArticlesToddlerTantrumsRoute
  '/articles/vaccination-guide': typeof ArticlesVaccinationGuideRoute
  '/articles/when-to-call-pediatrician': typeof ArticlesWhenToCallPediatricianRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/authors': typeof AuthorsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/medical-disclaimer': typeof MedicalDisclaimerRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/_template': typeof ArticlesTemplateRoute
  '/articles/adhd-in-toddlers': typeof ArticlesAdhdInToddlersRoute
  '/articles/baby-growth-spurts': typeof ArticlesBabyGrowthSpurtsRoute
  '/articles/baby-milestones-by-month': typeof ArticlesBabyMilestonesByMonthRoute
  '/articles/baby-sleep-guide': typeof ArticlesBabySleepGuideRoute
  '/articles/baby-teething-symptoms': typeof ArticlesBabyTeethingSymptomsRoute
  '/articles/best-baby-books': typeof ArticlesBestBabyBooksRoute
  '/articles/best-baby-bottles': typeof ArticlesBestBabyBottlesRoute
  '/articles/best-baby-carriers': typeof ArticlesBestBabyCarriersRoute
  '/articles/best-baby-food-makers': typeof ArticlesBestBabyFoodMakersRoute
  '/articles/best-baby-formula': typeof ArticlesBestBabyFormulaRoute
  '/articles/best-baby-monitors': typeof ArticlesBestBabyMonitorsRoute
  '/articles/best-baby-monitors-camera': typeof ArticlesBestBabyMonitorsCameraRoute
  '/articles/best-baby-sleep-products': typeof ArticlesBestBabySleepProductsRoute
  '/articles/best-baby-thermometers': typeof ArticlesBestBabyThermometersRoute
  '/articles/best-baby-walkers': typeof ArticlesBestBabyWalkersRoute
  '/articles/best-breast-pumps': typeof ArticlesBestBreastPumpsRoute
  '/articles/best-breast-pumps-working-moms': typeof ArticlesBestBreastPumpsWorkingMomsRoute
  '/articles/best-car-seats': typeof ArticlesBestCarSeatsRoute
  '/articles/best-convertible-car-seats': typeof ArticlesBestConvertibleCarSeatsRoute
  '/articles/best-cribs-bassinets': typeof ArticlesBestCribsBassinetsRoute
  '/articles/best-diaper-bags': typeof ArticlesBestDiaperBagsRoute
  '/articles/best-educational-toys': typeof ArticlesBestEducationalToysRoute
  '/articles/best-high-chairs': typeof ArticlesBestHighChairsRoute
  '/articles/best-strollers': typeof ArticlesBestStrollersRoute
  '/articles/birth-plan-template': typeof ArticlesBirthPlanTemplateRoute
  '/articles/breastfeeding-vs-formula': typeof ArticlesBreastfeedingVsFormulaRoute
  '/articles/child-development-milestones': typeof ArticlesChildDevelopmentMilestonesRoute
  '/articles/child-fever-guide': typeof ArticlesChildFeverGuideRoute
  '/articles/child-fever-home-remedies': typeof ArticlesChildFeverHomeRemediesRoute
  '/articles/child-nutrition-guide': typeof ArticlesChildNutritionGuideRoute
  '/articles/co-sleeping-safety': typeof ArticlesCoSleepingSafetyRoute
  '/articles/early-intervention': typeof ArticlesEarlyInterventionRoute
  '/articles/fever-in-children': typeof ArticlesFeverInChildrenRoute
  '/articles/newborn-care-guide': typeof ArticlesNewbornCareGuideRoute
  '/articles/newborn-essentials-checklist': typeof ArticlesNewbornEssentialsChecklistRoute
  '/articles/newborn-sleep': typeof ArticlesNewbornSleepRoute
  '/articles/parenting-hacks': typeof ArticlesParentingHacksRoute
  '/articles/parenting-survival-guide': typeof ArticlesParentingSurvivalGuideRoute
  '/articles/postpartum-hair-loss': typeof ArticlesPostpartumHairLossRoute
  '/articles/postpartum-mental-health': typeof ArticlesPostpartumMentalHealthRoute
  '/articles/postpartum-recovery': typeof ArticlesPostpartumRecoveryRoute
  '/articles/potty-training-autism': typeof ArticlesPottyTrainingAutismRoute
  '/articles/potty-training-guide': typeof ArticlesPottyTrainingGuideRoute
  '/articles/pregnancy-symptoms-by-trimester': typeof ArticlesPregnancySymptomsByTrimesterRoute
  '/articles/preschool-readiness': typeof ArticlesPreschoolReadinessRoute
  '/articles/returning-to-work-after-baby': typeof ArticlesReturningToWorkAfterBabyRoute
  '/articles/sensory-processing-disorder': typeof ArticlesSensoryProcessingDisorderRoute
  '/articles/signs-of-autism-in-toddlers': typeof ArticlesSignsOfAutismInToddlersRoute
  '/articles/sleep-training-methods': typeof ArticlesSleepTrainingMethodsRoute
  '/articles/speech-delay-toddler': typeof ArticlesSpeechDelayToddlerRoute
  '/articles/speech-development-guide': typeof ArticlesSpeechDevelopmentGuideRoute
  '/articles/speech-milestones': typeof ArticlesSpeechMilestonesRoute
  '/articles/starting-solids': typeof ArticlesStartingSolidsRoute
  '/articles/starting-solids-guide': typeof ArticlesStartingSolidsGuideRoute
  '/articles/toddler-activities-at-home': typeof ArticlesToddlerActivitiesAtHomeRoute
  '/articles/toddler-biting': typeof ArticlesToddlerBitingRoute
  '/articles/toddler-hitting': typeof ArticlesToddlerHittingRoute
  '/articles/toddler-not-talking': typeof ArticlesToddlerNotTalkingRoute
  '/articles/toddler-nutrition-tips': typeof ArticlesToddlerNutritionTipsRoute
  '/articles/toddler-picky-eating': typeof ArticlesToddlerPickyEatingRoute
  '/articles/toddler-regression': typeof ArticlesToddlerRegressionRoute
  '/articles/toddler-screen-time': typeof ArticlesToddlerScreenTimeRoute
  '/articles/toddler-sleep-problems': typeof ArticlesToddlerSleepProblemsRoute
  '/articles/toddler-sleep-regression': typeof ArticlesToddlerSleepRegressionRoute
  '/articles/toddler-tantrums': typeof ArticlesToddlerTantrumsRoute
  '/articles/vaccination-guide': typeof ArticlesVaccinationGuideRoute
  '/articles/when-to-call-pediatrician': typeof ArticlesWhenToCallPediatricianRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/go/$slug': typeof GoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/affiliate-disclosure'
    | '/articles'
    | '/categories'
    | '/contact'
    | '/cookie-policy'
    | '/medical-disclaimer'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/subscribers'
    | '/articles/$slug'
    | '/articles/adhd-in-toddlers'
    | '/articles/baby-growth-spurts'
    | '/articles/baby-milestones-by-month'
    | '/articles/baby-sleep-guide'
    | '/articles/baby-teething-symptoms'
    | '/articles/best-baby-books'
    | '/articles/best-baby-bottles'
    | '/articles/best-baby-carriers'
    | '/articles/best-baby-food-makers'
    | '/articles/best-baby-formula'
    | '/articles/best-baby-monitors'
    | '/articles/best-baby-monitors-camera'
    | '/articles/best-baby-sleep-products'
    | '/articles/best-baby-thermometers'
    | '/articles/best-baby-walkers'
    | '/articles/best-breast-pumps'
    | '/articles/best-breast-pumps-working-moms'
    | '/articles/best-car-seats'
    | '/articles/best-convertible-car-seats'
    | '/articles/best-cribs-bassinets'
    | '/articles/best-diaper-bags'
    | '/articles/best-educational-toys'
    | '/articles/best-high-chairs'
    | '/articles/best-strollers'
    | '/articles/birth-plan-template'
    | '/articles/breastfeeding-vs-formula'
    | '/articles/child-development-milestones'
    | '/articles/child-fever-guide'
    | '/articles/child-fever-home-remedies'
    | '/articles/child-nutrition-guide'
    | '/articles/co-sleeping-safety'
    | '/articles/early-intervention'
    | '/articles/fever-in-children'
    | '/articles/newborn-care-guide'
    | '/articles/newborn-essentials-checklist'
    | '/articles/newborn-sleep'
    | '/articles/parenting-hacks'
    | '/articles/parenting-survival-guide'
    | '/articles/postpartum-hair-loss'
    | '/articles/postpartum-mental-health'
    | '/articles/postpartum-recovery'
    | '/articles/potty-training-autism'
    | '/articles/potty-training-guide'
    | '/articles/pregnancy-symptoms-by-trimester'
    | '/articles/preschool-readiness'
    | '/articles/returning-to-work-after-baby'
    | '/articles/sensory-processing-disorder'
    | '/articles/signs-of-autism-in-toddlers'
    | '/articles/sleep-training-methods'
    | '/articles/speech-delay-toddler'
    | '/articles/speech-development-guide'
    | '/articles/speech-milestones'
    | '/articles/starting-solids'
    | '/articles/starting-solids-guide'
    | '/articles/toddler-activities-at-home'
    | '/articles/toddler-biting'
    | '/articles/toddler-hitting'
    | '/articles/toddler-not-talking'
    | '/articles/toddler-nutrition-tips'
    | '/articles/toddler-picky-eating'
    | '/articles/toddler-regression'
    | '/articles/toddler-screen-time'
    | '/articles/toddler-sleep-problems'
    | '/articles/toddler-sleep-regression'
    | '/articles/toddler-tantrums'
    | '/articles/vaccination-guide'
    | '/articles/when-to-call-pediatrician'
    | '/authors/$slug'
    | '/categories/$slug'
    | '/go/$slug'
    | '/admin/'
    | '/articles/'
    | '/authors/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/categories'
    | '/contact'
    | '/cookie-policy'
    | '/medical-disclaimer'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/subscribers'
    | '/articles/$slug'
    | '/articles'
    | '/articles/adhd-in-toddlers'
    | '/articles/baby-growth-spurts'
    | '/articles/baby-milestones-by-month'
    | '/articles/baby-sleep-guide'
    | '/articles/baby-teething-symptoms'
    | '/articles/best-baby-books'
    | '/articles/best-baby-bottles'
    | '/articles/best-baby-carriers'
    | '/articles/best-baby-food-makers'
    | '/articles/best-baby-formula'
    | '/articles/best-baby-monitors'
    | '/articles/best-baby-monitors-camera'
    | '/articles/best-baby-sleep-products'
    | '/articles/best-baby-thermometers'
    | '/articles/best-baby-walkers'
    | '/articles/best-breast-pumps'
    | '/articles/best-breast-pumps-working-moms'
    | '/articles/best-car-seats'
    | '/articles/best-convertible-car-seats'
    | '/articles/best-cribs-bassinets'
    | '/articles/best-diaper-bags'
    | '/articles/best-educational-toys'
    | '/articles/best-high-chairs'
    | '/articles/best-strollers'
    | '/articles/birth-plan-template'
    | '/articles/breastfeeding-vs-formula'
    | '/articles/child-development-milestones'
    | '/articles/child-fever-guide'
    | '/articles/child-fever-home-remedies'
    | '/articles/child-nutrition-guide'
    | '/articles/co-sleeping-safety'
    | '/articles/early-intervention'
    | '/articles/fever-in-children'
    | '/articles/newborn-care-guide'
    | '/articles/newborn-essentials-checklist'
    | '/articles/newborn-sleep'
    | '/articles/parenting-hacks'
    | '/articles/parenting-survival-guide'
    | '/articles/postpartum-hair-loss'
    | '/articles/postpartum-mental-health'
    | '/articles/postpartum-recovery'
    | '/articles/potty-training-autism'
    | '/articles/potty-training-guide'
    | '/articles/pregnancy-symptoms-by-trimester'
    | '/articles/preschool-readiness'
    | '/articles/returning-to-work-after-baby'
    | '/articles/sensory-processing-disorder'
    | '/articles/signs-of-autism-in-toddlers'
    | '/articles/sleep-training-methods'
    | '/articles/speech-delay-toddler'
    | '/articles/speech-development-guide'
    | '/articles/speech-milestones'
    | '/articles/starting-solids'
    | '/articles/starting-solids-guide'
    | '/articles/toddler-activities-at-home'
    | '/articles/toddler-biting'
    | '/articles/toddler-hitting'
    | '/articles/toddler-not-talking'
    | '/articles/toddler-nutrition-tips'
    | '/articles/toddler-picky-eating'
    | '/articles/toddler-regression'
    | '/articles/toddler-screen-time'
    | '/articles/toddler-sleep-problems'
    | '/articles/toddler-sleep-regression'
    | '/articles/toddler-tantrums'
    | '/articles/vaccination-guide'
    | '/articles/when-to-call-pediatrician'
    | '/authors/$slug'
    | '/categories/$slug'
    | '/go/$slug'
    | '/admin'
    | '/authors'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/articles'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/affiliate-disclosure'
    | '/articles'
    | '/categories'
    | '/contact'
    | '/cookie-policy'
    | '/medical-disclaimer'
    | '/privacy'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/messages'
    | '/admin/subscribers'
    | '/articles/$slug'
    | '/articles/_template'
    | '/articles/adhd-in-toddlers'
    | '/articles/baby-growth-spurts'
    | '/articles/baby-milestones-by-month'
    | '/articles/baby-sleep-guide'
    | '/articles/baby-teething-symptoms'
    | '/articles/best-baby-books'
    | '/articles/best-baby-bottles'
    | '/articles/best-baby-carriers'
    | '/articles/best-baby-food-makers'
    | '/articles/best-baby-formula'
    | '/articles/best-baby-monitors'
    | '/articles/best-baby-monitors-camera'
    | '/articles/best-baby-sleep-products'
    | '/articles/best-baby-thermometers'
    | '/articles/best-baby-walkers'
    | '/articles/best-breast-pumps'
    | '/articles/best-breast-pumps-working-moms'
    | '/articles/best-car-seats'
    | '/articles/best-convertible-car-seats'
    | '/articles/best-cribs-bassinets'
    | '/articles/best-diaper-bags'
    | '/articles/best-educational-toys'
    | '/articles/best-high-chairs'
    | '/articles/best-strollers'
    | '/articles/birth-plan-template'
    | '/articles/breastfeeding-vs-formula'
    | '/articles/child-development-milestones'
    | '/articles/child-fever-guide'
    | '/articles/child-fever-home-remedies'
    | '/articles/child-nutrition-guide'
    | '/articles/co-sleeping-safety'
    | '/articles/early-intervention'
    | '/articles/fever-in-children'
    | '/articles/newborn-care-guide'
    | '/articles/newborn-essentials-checklist'
    | '/articles/newborn-sleep'
    | '/articles/parenting-hacks'
    | '/articles/parenting-survival-guide'
    | '/articles/postpartum-hair-loss'
    | '/articles/postpartum-mental-health'
    | '/articles/postpartum-recovery'
    | '/articles/potty-training-autism'
    | '/articles/potty-training-guide'
    | '/articles/pregnancy-symptoms-by-trimester'
    | '/articles/preschool-readiness'
    | '/articles/returning-to-work-after-baby'
    | '/articles/sensory-processing-disorder'
    | '/articles/signs-of-autism-in-toddlers'
    | '/articles/sleep-training-methods'
    | '/articles/speech-delay-toddler'
    | '/articles/speech-development-guide'
    | '/articles/speech-milestones'
    | '/articles/starting-solids'
    | '/articles/starting-solids-guide'
    | '/articles/toddler-activities-at-home'
    | '/articles/toddler-biting'
    | '/articles/toddler-hitting'
    | '/articles/toddler-not-talking'
    | '/articles/toddler-nutrition-tips'
    | '/articles/toddler-picky-eating'
    | '/articles/toddler-regression'
    | '/articles/toddler-screen-time'
    | '/articles/toddler-sleep-problems'
    | '/articles/toddler-sleep-regression'
    | '/articles/toddler-tantrums'
    | '/articles/vaccination-guide'
    | '/articles/when-to-call-pediatrician'
    | '/authors/$slug'
    | '/categories/$slug'
    | '/go/$slug'
    | '/admin/'
    | '/articles/'
    | '/authors/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  MedicalDisclaimerRoute: typeof MedicalDisclaimerRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  GoSlugRoute: typeof GoSlugRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-disclaimer': {
      id: '/medical-disclaimer'
      path: '/medical-disclaimer'
      fullPath: '/medical-disclaimer'
      preLoaderRoute: typeof MedicalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/go/$slug': {
      id: '/go/$slug'
      path: '/go/$slug'
      fullPath: '/go/$slug'
      preLoaderRoute: typeof GoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/when-to-call-pediatrician': {
      id: '/articles/when-to-call-pediatrician'
      path: '/when-to-call-pediatrician'
      fullPath: '/articles/when-to-call-pediatrician'
      preLoaderRoute: typeof ArticlesWhenToCallPediatricianRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/vaccination-guide': {
      id: '/articles/vaccination-guide'
      path: '/vaccination-guide'
      fullPath: '/articles/vaccination-guide'
      preLoaderRoute: typeof ArticlesVaccinationGuideRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-tantrums': {
      id: '/articles/toddler-tantrums'
      path: '/toddler-tantrums'
      fullPath: '/articles/toddler-tantrums'
      preLoaderRoute: typeof ArticlesToddlerTantrumsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-sleep-regression': {
      id: '/articles/toddler-sleep-regression'
      path: '/toddler-sleep-regression'
      fullPath: '/articles/toddler-sleep-regression'
      preLoaderRoute: typeof ArticlesToddlerSleepRegressionRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-sleep-problems': {
      id: '/articles/toddler-sleep-problems'
      path: '/toddler-sleep-problems'
      fullPath: '/articles/toddler-sleep-problems'
      preLoaderRoute: typeof ArticlesToddlerSleepProblemsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-screen-time': {
      id: '/articles/toddler-screen-time'
      path: '/toddler-screen-time'
      fullPath: '/articles/toddler-screen-time'
      preLoaderRoute: typeof ArticlesToddlerScreenTimeRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-regression': {
      id: '/articles/toddler-regression'
      path: '/toddler-regression'
      fullPath: '/articles/toddler-regression'
      preLoaderRoute: typeof ArticlesToddlerRegressionRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-picky-eating': {
      id: '/articles/toddler-picky-eating'
      path: '/toddler-picky-eating'
      fullPath: '/articles/toddler-picky-eating'
      preLoaderRoute: typeof ArticlesToddlerPickyEatingRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-nutrition-tips': {
      id: '/articles/toddler-nutrition-tips'
      path: '/toddler-nutrition-tips'
      fullPath: '/articles/toddler-nutrition-tips'
      preLoaderRoute: typeof ArticlesToddlerNutritionTipsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-not-talking': {
      id: '/articles/toddler-not-talking'
      path: '/toddler-not-talking'
      fullPath: '/articles/toddler-not-talking'
      preLoaderRoute: typeof ArticlesToddlerNotTalkingRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-hitting': {
      id: '/articles/toddler-hitting'
      path: '/toddler-hitting'
      fullPath: '/articles/toddler-hitting'
      preLoaderRoute: typeof ArticlesToddlerHittingRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-biting': {
      id: '/articles/toddler-biting'
      path: '/toddler-biting'
      fullPath: '/articles/toddler-biting'
      preLoaderRoute: typeof ArticlesToddlerBitingRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/toddler-activities-at-home': {
      id: '/articles/toddler-activities-at-home'
      path: '/toddler-activities-at-home'
      fullPath: '/articles/toddler-activities-at-home'
      preLoaderRoute: typeof ArticlesToddlerActivitiesAtHomeRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/starting-solids-guide': {
      id: '/articles/starting-solids-guide'
      path: '/starting-solids-guide'
      fullPath: '/articles/starting-solids-guide'
      preLoaderRoute: typeof ArticlesStartingSolidsGuideRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/starting-solids': {
      id: '/articles/starting-solids'
      path: '/starting-solids'
      fullPath: '/articles/starting-solids'
      preLoaderRoute: typeof ArticlesStartingSolidsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/speech-milestones': {
      id: '/articles/speech-milestones'
      path: '/speech-milestones'
      fullPath: '/articles/speech-milestones'
      preLoaderRoute: typeof ArticlesSpeechMilestonesRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/speech-development-guide': {
      id: '/articles/speech-development-guide'
      path: '/speech-development-guide'
      fullPath: '/articles/speech-development-guide'
      preLoaderRoute: typeof ArticlesSpeechDevelopmentGuideRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/speech-delay-toddler': {
      id: '/articles/speech-delay-toddler'
      path: '/speech-delay-toddler'
      fullPath: '/articles/speech-delay-toddler'
      preLoaderRoute: typeof ArticlesSpeechDelayToddlerRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/sleep-training-methods': {
      id: '/articles/sleep-training-methods'
      path: '/sleep-training-methods'
      fullPath: '/articles/sleep-training-methods'
      preLoaderRoute: typeof ArticlesSleepTrainingMethodsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/signs-of-autism-in-toddlers': {
      id: '/articles/signs-of-autism-in-toddlers'
      path: '/signs-of-autism-in-toddlers'
      fullPath: '/articles/signs-of-autism-in-toddlers'
      preLoaderRoute: typeof ArticlesSignsOfAutismInToddlersRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/sensory-processing-disorder': {
      id: '/articles/sensory-processing-disorder'
      path: '/sensory-processing-disorder'
      fullPath: '/articles/sensory-processing-disorder'
      preLoaderRoute: typeof ArticlesSensoryProcessingDisorderRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/returning-to-work-after-baby': {
      id: '/articles/returning-to-work-after-baby'
      path: '/returning-to-work-after-baby'
      fullPath: '/articles/returning-to-work-after-baby'
      preLoaderRoute: typeof ArticlesReturningToWorkAfterBabyRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/preschool-readiness': {
      id: '/articles/preschool-readiness'
      path: '/preschool-readiness'
      fullPath: '/articles/preschool-readiness'
      preLoaderRoute: typeof ArticlesPreschoolReadinessRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/pregnancy-symptoms-by-trimester': {
      id: '/articles/pregnancy-symptoms-by-trimester'
      path: '/pregnancy-symptoms-by-trimester'
      fullPath: '/articles/pregnancy-symptoms-by-trimester'
      preLoaderRoute: typeof ArticlesPregnancySymptomsByTrimesterRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/potty-training-guide': {
      id: '/articles/potty-training-guide'
      path: '/potty-training-guide'
      fullPath: '/articles/potty-training-guide'
      preLoaderRoute: typeof ArticlesPottyTrainingGuideRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/potty-training-autism': {
      id: '/articles/potty-training-autism'
      path: '/potty-training-autism'
      fullPath: '/articles/potty-training-autism'
      preLoaderRoute: typeof ArticlesPottyTrainingAutismRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/postpartum-recovery': {
      id: '/articles/postpartum-recovery'
      path: '/postpartum-recovery'
      fullPath: '/articles/postpartum-recovery'
      preLoaderRoute: typeof ArticlesPostpartumRecoveryRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/postpartum-mental-health': {
      id: '/articles/postpartum-mental-health'
      path: '/postpartum-mental-health'
      fullPath: '/articles/postpartum-mental-health'
      preLoaderRoute: typeof ArticlesPostpartumMentalHealthRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/postpartum-hair-loss': {
      id: '/articles/postpartum-hair-loss'
      path: '/postpartum-hair-loss'
      fullPath: '/articles/postpartum-hair-loss'
      preLoaderRoute: typeof ArticlesPostpartumHairLossRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/parenting-survival-guide': {
      id: '/articles/parenting-survival-guide'
      path: '/parenting-survival-guide'
      fullPath: '/articles/parenting-survival-guide'
      preLoaderRoute: typeof ArticlesParentingSurvivalGuideRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/parenting-hacks': {
      id: '/articles/parenting-hacks'
      path: '/parenting-hacks'
      fullPath: '/articles/parenting-hacks'
      preLoaderRoute: typeof ArticlesParentingHacksRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/newborn-sleep': {
      id: '/articles/newborn-sleep'
      path: '/newborn-sleep'
      fullPath: '/articles/newborn-sleep'
      preLoaderRoute: typeof ArticlesNewbornSleepRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/newborn-essentials-checklist': {
      id: '/articles/newborn-essentials-checklist'
      path: '/newborn-essentials-checklist'
      fullPath: '/articles/newborn-essentials-checklist'
      preLoaderRoute: typeof ArticlesNewbornEssentialsChecklistRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/newborn-care-guide': {
      id: '/articles/newborn-care-guide'
      path: '/newborn-care-guide'
      fullPath: '/articles/newborn-care-guide'
      preLoaderRoute: typeof ArticlesNewbornCareGuideRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/fever-in-children': {
      id: '/articles/fever-in-children'
      path: '/fever-in-children'
      fullPath: '/articles/fever-in-children'
      preLoaderRoute: typeof ArticlesFeverInChildrenRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/early-intervention': {
      id: '/articles/early-intervention'
      path: '/early-intervention'
      fullPath: '/articles/early-intervention'
      preLoaderRoute: typeof ArticlesEarlyInterventionRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/co-sleeping-safety': {
      id: '/articles/co-sleeping-safety'
      path: '/co-sleeping-safety'
      fullPath: '/articles/co-sleeping-safety'
      preLoaderRoute: typeof ArticlesCoSleepingSafetyRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/child-nutrition-guide': {
      id: '/articles/child-nutrition-guide'
      path: '/child-nutrition-guide'
      fullPath: '/articles/child-nutrition-guide'
      preLoaderRoute: typeof ArticlesChildNutritionGuideRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/child-fever-home-remedies': {
      id: '/articles/child-fever-home-remedies'
      path: '/child-fever-home-remedies'
      fullPath: '/articles/child-fever-home-remedies'
      preLoaderRoute: typeof ArticlesChildFeverHomeRemediesRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/child-fever-guide': {
      id: '/articles/child-fever-guide'
      path: '/child-fever-guide'
      fullPath: '/articles/child-fever-guide'
      preLoaderRoute: typeof ArticlesChildFeverGuideRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/child-development-milestones': {
      id: '/articles/child-development-milestones'
      path: '/child-development-milestones'
      fullPath: '/articles/child-development-milestones'
      preLoaderRoute: typeof ArticlesChildDevelopmentMilestonesRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/breastfeeding-vs-formula': {
      id: '/articles/breastfeeding-vs-formula'
      path: '/breastfeeding-vs-formula'
      fullPath: '/articles/breastfeeding-vs-formula'
      preLoaderRoute: typeof ArticlesBreastfeedingVsFormulaRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/birth-plan-template': {
      id: '/articles/birth-plan-template'
      path: '/birth-plan-template'
      fullPath: '/articles/birth-plan-template'
      preLoaderRoute: typeof ArticlesBirthPlanTemplateRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-strollers': {
      id: '/articles/best-strollers'
      path: '/best-strollers'
      fullPath: '/articles/best-strollers'
      preLoaderRoute: typeof ArticlesBestStrollersRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-high-chairs': {
      id: '/articles/best-high-chairs'
      path: '/best-high-chairs'
      fullPath: '/articles/best-high-chairs'
      preLoaderRoute: typeof ArticlesBestHighChairsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-educational-toys': {
      id: '/articles/best-educational-toys'
      path: '/best-educational-toys'
      fullPath: '/articles/best-educational-toys'
      preLoaderRoute: typeof ArticlesBestEducationalToysRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-diaper-bags': {
      id: '/articles/best-diaper-bags'
      path: '/best-diaper-bags'
      fullPath: '/articles/best-diaper-bags'
      preLoaderRoute: typeof ArticlesBestDiaperBagsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-cribs-bassinets': {
      id: '/articles/best-cribs-bassinets'
      path: '/best-cribs-bassinets'
      fullPath: '/articles/best-cribs-bassinets'
      preLoaderRoute: typeof ArticlesBestCribsBassinetsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-convertible-car-seats': {
      id: '/articles/best-convertible-car-seats'
      path: '/best-convertible-car-seats'
      fullPath: '/articles/best-convertible-car-seats'
      preLoaderRoute: typeof ArticlesBestConvertibleCarSeatsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-car-seats': {
      id: '/articles/best-car-seats'
      path: '/best-car-seats'
      fullPath: '/articles/best-car-seats'
      preLoaderRoute: typeof ArticlesBestCarSeatsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-breast-pumps-working-moms': {
      id: '/articles/best-breast-pumps-working-moms'
      path: '/best-breast-pumps-working-moms'
      fullPath: '/articles/best-breast-pumps-working-moms'
      preLoaderRoute: typeof ArticlesBestBreastPumpsWorkingMomsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-breast-pumps': {
      id: '/articles/best-breast-pumps'
      path: '/best-breast-pumps'
      fullPath: '/articles/best-breast-pumps'
      preLoaderRoute: typeof ArticlesBestBreastPumpsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-walkers': {
      id: '/articles/best-baby-walkers'
      path: '/best-baby-walkers'
      fullPath: '/articles/best-baby-walkers'
      preLoaderRoute: typeof ArticlesBestBabyWalkersRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-thermometers': {
      id: '/articles/best-baby-thermometers'
      path: '/best-baby-thermometers'
      fullPath: '/articles/best-baby-thermometers'
      preLoaderRoute: typeof ArticlesBestBabyThermometersRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-sleep-products': {
      id: '/articles/best-baby-sleep-products'
      path: '/best-baby-sleep-products'
      fullPath: '/articles/best-baby-sleep-products'
      preLoaderRoute: typeof ArticlesBestBabySleepProductsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-monitors-camera': {
      id: '/articles/best-baby-monitors-camera'
      path: '/best-baby-monitors-camera'
      fullPath: '/articles/best-baby-monitors-camera'
      preLoaderRoute: typeof ArticlesBestBabyMonitorsCameraRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-monitors': {
      id: '/articles/best-baby-monitors'
      path: '/best-baby-monitors'
      fullPath: '/articles/best-baby-monitors'
      preLoaderRoute: typeof ArticlesBestBabyMonitorsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-formula': {
      id: '/articles/best-baby-formula'
      path: '/best-baby-formula'
      fullPath: '/articles/best-baby-formula'
      preLoaderRoute: typeof ArticlesBestBabyFormulaRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-food-makers': {
      id: '/articles/best-baby-food-makers'
      path: '/best-baby-food-makers'
      fullPath: '/articles/best-baby-food-makers'
      preLoaderRoute: typeof ArticlesBestBabyFoodMakersRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-carriers': {
      id: '/articles/best-baby-carriers'
      path: '/best-baby-carriers'
      fullPath: '/articles/best-baby-carriers'
      preLoaderRoute: typeof ArticlesBestBabyCarriersRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-bottles': {
      id: '/articles/best-baby-bottles'
      path: '/best-baby-bottles'
      fullPath: '/articles/best-baby-bottles'
      preLoaderRoute: typeof ArticlesBestBabyBottlesRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-baby-books': {
      id: '/articles/best-baby-books'
      path: '/best-baby-books'
      fullPath: '/articles/best-baby-books'
      preLoaderRoute: typeof ArticlesBestBabyBooksRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/baby-teething-symptoms': {
      id: '/articles/baby-teething-symptoms'
      path: '/baby-teething-symptoms'
      fullPath: '/articles/baby-teething-symptoms'
      preLoaderRoute: typeof ArticlesBabyTeethingSymptomsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/baby-sleep-guide': {
      id: '/articles/baby-sleep-guide'
      path: '/baby-sleep-guide'
      fullPath: '/articles/baby-sleep-guide'
      preLoaderRoute: typeof ArticlesBabySleepGuideRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/baby-milestones-by-month': {
      id: '/articles/baby-milestones-by-month'
      path: '/baby-milestones-by-month'
      fullPath: '/articles/baby-milestones-by-month'
      preLoaderRoute: typeof ArticlesBabyMilestonesByMonthRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/baby-growth-spurts': {
      id: '/articles/baby-growth-spurts'
      path: '/baby-growth-spurts'
      fullPath: '/articles/baby-growth-spurts'
      preLoaderRoute: typeof ArticlesBabyGrowthSpurtsRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/adhd-in-toddlers': {
      id: '/articles/adhd-in-toddlers'
      path: '/adhd-in-toddlers'
      fullPath: '/articles/adhd-in-toddlers'
      preLoaderRoute: typeof ArticlesAdhdInToddlersRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/_template': {
      id: '/articles/_template'
      path: ''
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesTemplateRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesTemplateRoute: typeof ArticlesTemplateRoute
  ArticlesAdhdInToddlersRoute: typeof ArticlesAdhdInToddlersRoute
  ArticlesBabyGrowthSpurtsRoute: typeof ArticlesBabyGrowthSpurtsRoute
  ArticlesBabyMilestonesByMonthRoute: typeof ArticlesBabyMilestonesByMonthRoute
  ArticlesBabySleepGuideRoute: typeof ArticlesBabySleepGuideRoute
  ArticlesBabyTeethingSymptomsRoute: typeof ArticlesBabyTeethingSymptomsRoute
  ArticlesBestBabyBooksRoute: typeof ArticlesBestBabyBooksRoute
  ArticlesBestBabyBottlesRoute: typeof ArticlesBestBabyBottlesRoute
  ArticlesBestBabyCarriersRoute: typeof ArticlesBestBabyCarriersRoute
  ArticlesBestBabyFoodMakersRoute: typeof ArticlesBestBabyFoodMakersRoute
  ArticlesBestBabyFormulaRoute: typeof ArticlesBestBabyFormulaRoute
  ArticlesBestBabyMonitorsRoute: typeof ArticlesBestBabyMonitorsRoute
  ArticlesBestBabyMonitorsCameraRoute: typeof ArticlesBestBabyMonitorsCameraRoute
  ArticlesBestBabySleepProductsRoute: typeof ArticlesBestBabySleepProductsRoute
  ArticlesBestBabyThermometersRoute: typeof ArticlesBestBabyThermometersRoute
  ArticlesBestBabyWalkersRoute: typeof ArticlesBestBabyWalkersRoute
  ArticlesBestBreastPumpsRoute: typeof ArticlesBestBreastPumpsRoute
  ArticlesBestBreastPumpsWorkingMomsRoute: typeof ArticlesBestBreastPumpsWorkingMomsRoute
  ArticlesBestCarSeatsRoute: typeof ArticlesBestCarSeatsRoute
  ArticlesBestConvertibleCarSeatsRoute: typeof ArticlesBestConvertibleCarSeatsRoute
  ArticlesBestCribsBassinetsRoute: typeof ArticlesBestCribsBassinetsRoute
  ArticlesBestDiaperBagsRoute: typeof ArticlesBestDiaperBagsRoute
  ArticlesBestEducationalToysRoute: typeof ArticlesBestEducationalToysRoute
  ArticlesBestHighChairsRoute: typeof ArticlesBestHighChairsRoute
  ArticlesBestStrollersRoute: typeof ArticlesBestStrollersRoute
  ArticlesBirthPlanTemplateRoute: typeof ArticlesBirthPlanTemplateRoute
  ArticlesBreastfeedingVsFormulaRoute: typeof ArticlesBreastfeedingVsFormulaRoute
  ArticlesChildDevelopmentMilestonesRoute: typeof ArticlesChildDevelopmentMilestonesRoute
  ArticlesChildFeverGuideRoute: typeof ArticlesChildFeverGuideRoute
  ArticlesChildFeverHomeRemediesRoute: typeof ArticlesChildFeverHomeRemediesRoute
  ArticlesChildNutritionGuideRoute: typeof ArticlesChildNutritionGuideRoute
  ArticlesCoSleepingSafetyRoute: typeof ArticlesCoSleepingSafetyRoute
  ArticlesEarlyInterventionRoute: typeof ArticlesEarlyInterventionRoute
  ArticlesFeverInChildrenRoute: typeof ArticlesFeverInChildrenRoute
  ArticlesNewbornCareGuideRoute: typeof ArticlesNewbornCareGuideRoute
  ArticlesNewbornEssentialsChecklistRoute: typeof ArticlesNewbornEssentialsChecklistRoute
  ArticlesNewbornSleepRoute: typeof ArticlesNewbornSleepRoute
  ArticlesParentingHacksRoute: typeof ArticlesParentingHacksRoute
  ArticlesParentingSurvivalGuideRoute: typeof ArticlesParentingSurvivalGuideRoute
  ArticlesPostpartumHairLossRoute: typeof ArticlesPostpartumHairLossRoute
  ArticlesPostpartumMentalHealthRoute: typeof ArticlesPostpartumMentalHealthRoute
  ArticlesPostpartumRecoveryRoute: typeof ArticlesPostpartumRecoveryRoute
  ArticlesPottyTrainingAutismRoute: typeof ArticlesPottyTrainingAutismRoute
  ArticlesPottyTrainingGuideRoute: typeof ArticlesPottyTrainingGuideRoute
  ArticlesPregnancySymptomsByTrimesterRoute: typeof ArticlesPregnancySymptomsByTrimesterRoute
  ArticlesPreschoolReadinessRoute: typeof ArticlesPreschoolReadinessRoute
  ArticlesReturningToWorkAfterBabyRoute: typeof ArticlesReturningToWorkAfterBabyRoute
  ArticlesSensoryProcessingDisorderRoute: typeof ArticlesSensoryProcessingDisorderRoute
  ArticlesSignsOfAutismInToddlersRoute: typeof ArticlesSignsOfAutismInToddlersRoute
  ArticlesSleepTrainingMethodsRoute: typeof ArticlesSleepTrainingMethodsRoute
  ArticlesSpeechDelayToddlerRoute: typeof ArticlesSpeechDelayToddlerRoute
  ArticlesSpeechDevelopmentGuideRoute: typeof ArticlesSpeechDevelopmentGuideRoute
  ArticlesSpeechMilestonesRoute: typeof ArticlesSpeechMilestonesRoute
  ArticlesStartingSolidsRoute: typeof ArticlesStartingSolidsRoute
  ArticlesStartingSolidsGuideRoute: typeof ArticlesStartingSolidsGuideRoute
  ArticlesToddlerActivitiesAtHomeRoute: typeof ArticlesToddlerActivitiesAtHomeRoute
  ArticlesToddlerBitingRoute: typeof ArticlesToddlerBitingRoute
  ArticlesToddlerHittingRoute: typeof ArticlesToddlerHittingRoute
  ArticlesToddlerNotTalkingRoute: typeof ArticlesToddlerNotTalkingRoute
  ArticlesToddlerNutritionTipsRoute: typeof ArticlesToddlerNutritionTipsRoute
  ArticlesToddlerPickyEatingRoute: typeof ArticlesToddlerPickyEatingRoute
  ArticlesToddlerRegressionRoute: typeof ArticlesToddlerRegressionRoute
  ArticlesToddlerScreenTimeRoute: typeof ArticlesToddlerScreenTimeRoute
  ArticlesToddlerSleepProblemsRoute: typeof ArticlesToddlerSleepProblemsRoute
  ArticlesToddlerSleepRegressionRoute: typeof ArticlesToddlerSleepRegressionRoute
  ArticlesToddlerTantrumsRoute: typeof ArticlesToddlerTantrumsRoute
  ArticlesVaccinationGuideRoute: typeof ArticlesVaccinationGuideRoute
  ArticlesWhenToCallPediatricianRoute: typeof ArticlesWhenToCallPediatricianRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesTemplateRoute: ArticlesTemplateRoute,
  ArticlesAdhdInToddlersRoute: ArticlesAdhdInToddlersRoute,
  ArticlesBabyGrowthSpurtsRoute: ArticlesBabyGrowthSpurtsRoute,
  ArticlesBabyMilestonesByMonthRoute: ArticlesBabyMilestonesByMonthRoute,
  ArticlesBabySleepGuideRoute: ArticlesBabySleepGuideRoute,
  ArticlesBabyTeethingSymptomsRoute: ArticlesBabyTeethingSymptomsRoute,
  ArticlesBestBabyBooksRoute: ArticlesBestBabyBooksRoute,
  ArticlesBestBabyBottlesRoute: ArticlesBestBabyBottlesRoute,
  ArticlesBestBabyCarriersRoute: ArticlesBestBabyCarriersRoute,
  ArticlesBestBabyFoodMakersRoute: ArticlesBestBabyFoodMakersRoute,
  ArticlesBestBabyFormulaRoute: ArticlesBestBabyFormulaRoute,
  ArticlesBestBabyMonitorsRoute: ArticlesBestBabyMonitorsRoute,
  ArticlesBestBabyMonitorsCameraRoute: ArticlesBestBabyMonitorsCameraRoute,
  ArticlesBestBabySleepProductsRoute: ArticlesBestBabySleepProductsRoute,
  ArticlesBestBabyThermometersRoute: ArticlesBestBabyThermometersRoute,
  ArticlesBestBabyWalkersRoute: ArticlesBestBabyWalkersRoute,
  ArticlesBestBreastPumpsRoute: ArticlesBestBreastPumpsRoute,
  ArticlesBestBreastPumpsWorkingMomsRoute:
    ArticlesBestBreastPumpsWorkingMomsRoute,
  ArticlesBestCarSeatsRoute: ArticlesBestCarSeatsRoute,
  ArticlesBestConvertibleCarSeatsRoute: ArticlesBestConvertibleCarSeatsRoute,
  ArticlesBestCribsBassinetsRoute: ArticlesBestCribsBassinetsRoute,
  ArticlesBestDiaperBagsRoute: ArticlesBestDiaperBagsRoute,
  ArticlesBestEducationalToysRoute: ArticlesBestEducationalToysRoute,
  ArticlesBestHighChairsRoute: ArticlesBestHighChairsRoute,
  ArticlesBestStrollersRoute: ArticlesBestStrollersRoute,
  ArticlesBirthPlanTemplateRoute: ArticlesBirthPlanTemplateRoute,
  ArticlesBreastfeedingVsFormulaRoute: ArticlesBreastfeedingVsFormulaRoute,
  ArticlesChildDevelopmentMilestonesRoute:
    ArticlesChildDevelopmentMilestonesRoute,
  ArticlesChildFeverGuideRoute: ArticlesChildFeverGuideRoute,
  ArticlesChildFeverHomeRemediesRoute: ArticlesChildFeverHomeRemediesRoute,
  ArticlesChildNutritionGuideRoute: ArticlesChildNutritionGuideRoute,
  ArticlesCoSleepingSafetyRoute: ArticlesCoSleepingSafetyRoute,
  ArticlesEarlyInterventionRoute: ArticlesEarlyInterventionRoute,
  ArticlesFeverInChildrenRoute: ArticlesFeverInChildrenRoute,
  ArticlesNewbornCareGuideRoute: ArticlesNewbornCareGuideRoute,
  ArticlesNewbornEssentialsChecklistRoute:
    ArticlesNewbornEssentialsChecklistRoute,
  ArticlesNewbornSleepRoute: ArticlesNewbornSleepRoute,
  ArticlesParentingHacksRoute: ArticlesParentingHacksRoute,
  ArticlesParentingSurvivalGuideRoute: ArticlesParentingSurvivalGuideRoute,
  ArticlesPostpartumHairLossRoute: ArticlesPostpartumHairLossRoute,
  ArticlesPostpartumMentalHealthRoute: ArticlesPostpartumMentalHealthRoute,
  ArticlesPostpartumRecoveryRoute: ArticlesPostpartumRecoveryRoute,
  ArticlesPottyTrainingAutismRoute: ArticlesPottyTrainingAutismRoute,
  ArticlesPottyTrainingGuideRoute: ArticlesPottyTrainingGuideRoute,
  ArticlesPregnancySymptomsByTrimesterRoute:
    ArticlesPregnancySymptomsByTrimesterRoute,
  ArticlesPreschoolReadinessRoute: ArticlesPreschoolReadinessRoute,
  ArticlesReturningToWorkAfterBabyRoute: ArticlesReturningToWorkAfterBabyRoute,
  ArticlesSensoryProcessingDisorderRoute:
    ArticlesSensoryProcessingDisorderRoute,
  ArticlesSignsOfAutismInToddlersRoute: ArticlesSignsOfAutismInToddlersRoute,
  ArticlesSleepTrainingMethodsRoute: ArticlesSleepTrainingMethodsRoute,
  ArticlesSpeechDelayToddlerRoute: ArticlesSpeechDelayToddlerRoute,
  ArticlesSpeechDevelopmentGuideRoute: ArticlesSpeechDevelopmentGuideRoute,
  ArticlesSpeechMilestonesRoute: ArticlesSpeechMilestonesRoute,
  ArticlesStartingSolidsRoute: ArticlesStartingSolidsRoute,
  ArticlesStartingSolidsGuideRoute: ArticlesStartingSolidsGuideRoute,
  ArticlesToddlerActivitiesAtHomeRoute: ArticlesToddlerActivitiesAtHomeRoute,
  ArticlesToddlerBitingRoute: ArticlesToddlerBitingRoute,
  ArticlesToddlerHittingRoute: ArticlesToddlerHittingRoute,
  ArticlesToddlerNotTalkingRoute: ArticlesToddlerNotTalkingRoute,
  ArticlesToddlerNutritionTipsRoute: ArticlesToddlerNutritionTipsRoute,
  ArticlesToddlerPickyEatingRoute: ArticlesToddlerPickyEatingRoute,
  ArticlesToddlerRegressionRoute: ArticlesToddlerRegressionRoute,
  ArticlesToddlerScreenTimeRoute: ArticlesToddlerScreenTimeRoute,
  ArticlesToddlerSleepProblemsRoute: ArticlesToddlerSleepProblemsRoute,
  ArticlesToddlerSleepRegressionRoute: ArticlesToddlerSleepRegressionRoute,
  ArticlesToddlerTantrumsRoute: ArticlesToddlerTantrumsRoute,
  ArticlesVaccinationGuideRoute: ArticlesVaccinationGuideRoute,
  ArticlesWhenToCallPediatricianRoute: ArticlesWhenToCallPediatricianRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  MedicalDisclaimerRoute: MedicalDisclaimerRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  GoSlugRoute: GoSlugRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
